// Static slug+title list — no fs/path imports so this is safe for any page.
// Keep in sync with products.ts when adding new products.
export const PRODUCT_SLUGS: { slug: string; title: string }[] = [
  // BiziLuxe Extensions
  { slug: "tape-in-extensions",      title: "Tape-In Extensions" },
  { slug: "weft-extensions",         title: "Genius Weft Extensions" },
  { slug: "utip-extensions",         title: "U-Tip Extensions" },
  // BiziHair Extensions
  { slug: "bizihair-weft-extensions",    title: "BiziHair Weft Extensions" },
  { slug: "bizihair-tape-in-extensions", title: "BiziHair Tape-In Extensions" },
  { slug: "bizihair-keratin-extensions", title: "BiziHair Keratin Extensions" },
  // Bonnets & Accessories
  { slug: "slip-on-bonnet",          title: "Premium Slip-On Bonnet" },
  { slug: "tie-up-bonnet",           title: "Premium Tie-Up Bonnet" },
  { slug: "dortmund",                title: "Slip-On Bonnet (Black)" },
  { slug: "sectioning-clips",        title: "Sectioning Clips" },
  { slug: "neuschwanstein",          title: "BiziLuxe Gold Clips (20 pcs)" },
  { slug: "drachenfels",             title: "Rose Gold Sectioning Clips" },
  { slug: "gator-grip-clips",        title: "Gator Grip Clips" },
  { slug: "fine-mist-spray-bottle",  title: "Fine Mist Spray Bottle" },
  { slug: "bocholt",                 title: "Professional Elastic Hair Bands" },
  { slug: "hair-extension-thread",   title: "Hair Extension Thread" },
  { slug: "hair-weaving-needles",    title: "Hair Weaving Needles" },
  { slug: "berghain",                title: "BiziLuxe Cotton Thread for Sew-In" },
  // Brushes & Combs
  { slug: "mini-travel-brush",       title: "BiziLuxe Travel Brush & Comb" },
  { slug: "vent-brush",              title: "BiziLuxe Vent Brush" },
  { slug: "wooden-paddle-brush",     title: "BiziLuxe Wooden Paddle Brush" },
  { slug: "detangling-brush",        title: "BiziLuxe Detangling Brush" },
  { slug: "edge-brush-comb",         title: "Edge Brush & Comb" },
  { slug: "wide-tint-brush",         title: "Wide Tint Brush" },
  { slug: "celle",                   title: "BiziLuxe Styling Brush" },
  { slug: "biziluxe-styling-combs",  title: "BiziLuxe Styling Combs" },
  { slug: "hameln",                  title: "BiziLuxe Tail Comb" },
  { slug: "luebeck",                 title: "BiziLuxe Pocket Comb" },
  { slug: "biziluxe-professional-combs", title: "BiziLuxe Professional Combs" },
  // Salon Equipment
  { slug: "salon-apron",             title: "Professional Salon Apron" },
  { slug: "smart-bowl",              title: "Smart Bowl" },
  { slug: "salon-trolley-drawers",   title: "Salon Trolley with Drawers" },
  { slug: "salon-service-trolley",   title: "Salon Service Trolley" },
  { slug: "colour-mixing-trolley",   title: "Colour Mixing Trolley" },
  { slug: "hair-cutting-cape",       title: "Professional Hair Cutting Cape" },
  { slug: "detmold",                 title: "Tinting Bowl (Black & White)" },
  { slug: "essen",                   title: "Hair Cutting Cape (Textured)" },
  { slug: "herford",                 title: "Adjustable Wig Stand Tripod" },
  { slug: "muenster",                title: "Disposable Gloves (100 pcs)" },
  { slug: "recklinghausen",          title: "Open Shelf Salon Trolley" },
  { slug: "paderborn",               title: "Cross-Back Salon Apron" },
  { slug: "tinting-tray",            title: "Tinting Tray" },
  // Tools & Application
  { slug: "wesel",                   title: "Micro Rings Set" },
  { slug: "keratin-heat-shield",     title: "Keratin Heat Shield" },
  { slug: "eisenach",                title: "BiziLuxe Removal Tonic" },
  { slug: "taunus",                  title: "BiziLuxe K-Tip Remover" },
  { slug: "mannheim",                title: "BiziLuxe Double Sided Tape" },
  { slug: "speicherstadt",           title: "BiziLuxe Tape Scraper" },
  { slug: "hamburger-hafen",         title: "BiziLuxe Latch Hook Tool" },
  // Styling Tools
  { slug: "solingen",                title: "BiziLuxe Hair Straightener" },
  { slug: "wiesbaden",               title: "BiziLuxe Crimping Iron" },
  { slug: "glashuette",              title: "Keratin Bond Fusion Iron" },
  { slug: "ruhrstahl",               title: "BiziLuxe Gold Scissors" },
  { slug: "zollverein",              title: "BiziLuxe Extension Tool Kit" },
];
