export const GERMAN_COPY_PAIRS: [string, string][] = [
  ["Luxury human hair extensions crafted for women who refuse compromise. Sourced from the world's finest suppliers, installed by Berlin's most trusted specialists.", "Luxuriöse Echthaar-Extensions für Frauen, die keine Kompromisse eingehen. Von den besten Lieferanten weltweit, installiert von Berlins renommiertesten Spezialisten."],
  ["Luxury extensions crafted for women who refuse compromise.", "Luxuriöse Extensions für Frauen, die keine Kompromisse eingehen."],
  ["Luxury Hair. Premium Quality. Every Strand Designed Just For You.", "Luxuriöses Haar. Premium-Qualität. Jede Strähne für dich perfektioniert."],
  ["Luxury Hair. Premium Quality. Designed for You.", "Luxuriöses Haar. Premium-Qualität. Für dich gemacht."],
  ["Stay connected with OlivHairSupply Club.", "Bleib immer auf dem Laufenden mit dem OlivHairSupply Club."],
  ["Stay connected with Olivhairsupply Club.", "Bleib immer auf dem Laufenden mit dem OlivHairSupply Club."],
  ["Worldwide Shipping — Free Over €200", "Weltweiter Versand – kostenlos ab 200 €"],
  ["Worldwide Shipping â€” Free Over â‚¬200", "Weltweiter Versand – kostenlos ab 200 €"],
  ["Free EU shipping on orders over €200", "Kostenloser EU-Versand ab 200 €"],
  ["Free EU Shipping Over €200", "Kostenloser EU-Versand ab 200 €"],
  ["FREE EU SHIPPING OVER €200", "KOSTENLOSER EU-VERSAND AB 200 €"],
  ["Free EU shipping on orders over â‚¬200", "Kostenloser EU-Versand ab 200 €"],
  ["Free EU Shipping Over â‚¬200", "Kostenloser EU-Versand ab 200 €"],
  ["FREE EU SHIPPING OVER â‚¬200", "KOSTENLOSER EU-VERSAND AB 200 €"],
  ["FREE EU SHIPPING", "KOSTENLOSER EU-VERSAND"],
  ["Free EU Shipping", "Kostenloser EU-Versand"],
  ["100% Human Hair", "100 % Echthaar"],
  ["100% HUMAN HAIR", "100 % ECHTHAAR"],
  ["Expert Colour Matching", "Professionelle Farbberatung"],
  ["EXPERT COLOUR MATCHING", "PROFESSIONELLE FARBBERATUNG"],
  ["Worldwide Delivery", "Weltweite Lieferung"],
  ["WORLDWIDE DELIVERY", "WELTWEITE LIEFERUNG"],
  ["Berlin In-Store Experience", "Berlin Salon-Erlebnis"],
  ["BERLIN IN-STORE EXPERIENCE", "BERLIN SALON-ERLEBNIS"],
  ["BiziLuxe Collection", "BiziLuxe Kollektion"],
  ["Shop BiziLuxe Hair", "BiziLuxe entdecken"],
  ["SHOP BIZILUXE HAIR", "BIZILUXE ENTDECKEN"],
  ["SHOP BIZILUXE", "BIZILUXE ENTDECKEN"],
  ["Book an Appointment", "Termin buchen"],
  ["Book Appointment", "Termin buchen"],
  ["BOOK APPOINTMENT", "TERMIN BUCHEN"],
  ["Premium Hair.", "Premium-Haar."],
  ["Confidence.", "Eleganz."],
  ["Effortless", "Mühelose"],
  ["Become an Affiliate →", "Affiliate-Partner werden →"],
  ["Become an Affiliate â†’", "Affiliate-Partner werden →"],
  ["Become an Affiliate", "Affiliate werden"],
  ["Affiliate Programme", "Affiliate-Programm"],
  ["Affiliate Program", "Affiliate-Programm"],
  ["Social Responsibility", "Soziale Verantwortung"],
  ["Track Order", "Bestellung verfolgen"],
  ["Stay Connected", "Verbunden bleiben"],
  ["STAY CONNECTED", "VERBUNDEN BLEIBEN"],
  ["Contact Us", "Kontakt"],
  ["Our Story", "Unsere Geschichte"],
  ["Sustainability", "Nachhaltigkeit"],
  ["Wholesale", "Großhandel"],
  ["Training", "Schulungen"],
  ["Appointment", "Termin buchen"],
  ["Careers", "Karriere"],
  ["Journal", "Magazin"],
  ["Returns", "Rücksendungen"],
  ["Shipping", "Versand"],
  ["Rentals", "Clip-in-Verleih"],
  ["Services", "Dienstleistungen"],
  ["Affiliate", "Affiliate"],
  ["About", "Über uns"],
  ["ABOUT", "ÜBER UNS"],
  ["Press", "Presse"],
  ["More", "Mehr"],
  ["MORE", "MEHR"],
  ["Help", "Hilfe"],
  ["HELP", "HILFE"],
  ["Home", "Startseite"],
  ["Shop", "Shop"],
  ["FAQ", "FAQ"],
  ["Language & Currency", "Sprache & Währung"],
  ["Language", "Sprache"],
  ["Currency", "Währung"],
  ["Search", "Suche"],
  ["Log in", "Anmelden"],
  ["Account", "Konto"],
  ["Cart", "Warenkorb"],
  ["Cart (0)", "Warenkorb (0)"],
  ["Open menu", "Menü öffnen"],
  ["Close menu", "Menü schließen"],
  ["First name", "Vorname"],
  ["Email address", "E-Mail-Adresse"],
  ["Subscribe", "Abonnieren"],
  ["Subscribe →", "Abonnieren →"],
  ["Subscribe &rarr;", "Abonnieren &rarr;"],
  ["No spam. Unsubscribe at any time.", "Kein Spam. Du kannst dich jederzeit abmelden."],
  ["Privacy Policy", "Datenschutzerklärung"],
  ["Terms and Conditions", "Allgemeine Geschäftsbedingungen"],
  ["All rights reserved.", "Alle Rechte vorbehalten."],
  ["Partner With OlivHairSupply", "Partner von OlivHairSupply werden"],
  ["Partner With ", "Partner von "],
  ["Partner With", "Partner von"],
  ["Become a wholesaler", "Werde Großhandelspartner"],
  ["Become a Wholesaler", "Werde Großhandelspartner"],
  ["Log Into Wholesale Shop", "Zum Großhandelsshop anmelden"],
  ["Log into Wholesale Shop", "Zum Großhandelsshop anmelden"],
  ["BiziLuxe Clip-In Collection", "BiziLuxe Clip-in-Kollektion"],
  ["Book Rental Consultation", "Beratung zur Anmietung buchen"],
  ["Speak to Our Team", "Unser Team kontaktieren"],
  ["Book Your Consultation", "Beratung buchen"],
  ["Luxury Hair ", "Luxuriöse Extensions zum "],
  ["Luxury Hair", "Luxuriöse Extensions"],
  ["Rentals.", "Mieten."],
  ["Our Services", "Unsere Dienstleistungen"],
  ["Tailored to You.", "für dein perfektes Haar."],
  ["Services ", "Individuelle Lösungen "],
  ["Book Training Consultation", "Beratungsgespräch buchen"],
  ["Become professionally ", "Werde professionell "],
  ["Become professionally", "Werde professionell"],
  ["Certified.", "zertifiziert."],
  ["Enroll Now", "Jetzt anmelden"],
  ["Berlin, Est. 2016", "Berlin, gegründet 2016"],
  ["Born from", "Aus Leidenschaft"],
  ["a passion", "entstanden"],
  ["The BiziLuxe Edit", "Die BiziLuxe Kollektion"],
  ["The BiziLuxe", "Die BiziLuxe"],
  ["Edit", "Kollektion"],
  ["100 %Cuticle-Aligned Human Hair", "100 % Echthaar mit intakter Schuppenschicht"],
  ["100% Cuticle-Aligned Human Hair", "100 % Echthaar mit intakter Schuppenschicht"],
  ["Cuticle-Aligned Human Hair", "Echthaar mit intakter Schuppenschicht"],
  ["6Collections", "6 Kollektionen"],
  ["6 Collections", "6 Kollektionen"],
  ["Collections", "Kollektionen"],
  ["Collection", "Kollektion"],
  ["EUWorldwide Shipping", "Weltweiter Versand"],
  ["EU Worldwide Shipping", "Weltweiter Versand"],
  ["Free ShippingOn orders over €200", "Kostenloser Versand ab 200 €"],
  ["Free Shipping On orders over €200", "Kostenloser Versand ab 200 €"],
  ["Free ShippingOn orders over â‚¬200", "Kostenloser Versand ab 200 €"],
  ["Free Shipping On orders over â‚¬200", "Kostenloser Versand ab 200 €"],
  ["On orders over €200", "Ab Bestellungen über 200 €"],
  ["On orders over â‚¬200", "Ab Bestellungen über 200 €"],
  ["14 Day ReturnsUnused sealed products", "14 Tage Rückgaberecht für unbenutzte und versiegelte Produkte"],
  ["14 Day Returns", "14 Tage Rückgaberecht"],
  ["Unused sealed products", "Für unbenutzte und versiegelte Produkte"],
  ["Expert GuidanceBook a free consultation", "Persönliche Beratung – kostenlose Beratung buchen"],
  ["Expert Guidance", "Persönliche Beratung"],
  ["Book a free consultation", "Kostenlose Beratung buchen"],
  ["EthicallySourcedQuality guaranteed", "Ethisch bezogen – garantierte Qualität"],
  ["Ethically SourcedQuality guaranteed", "Ethisch bezogen – garantierte Qualität"],
  ["Ethically Sourced", "Ethisch bezogen"],
  ["Quality guaranteed", "Garantierte Qualität"],
];

const TRANSLATABLE_ATTRIBUTES = ["aria-label", "title", "placeholder", "alt"] as const;

export function translateAttributes(element: Element, pairs: [string, string][]) {
  for (const attribute of TRANSLATABLE_ATTRIBUTES) {
    const current = element.getAttribute(attribute);
    if (!current) continue;
    let next = current;
    for (const [from, to] of pairs) {
      if (next.includes(from)) next = next.split(from).join(to);
    }
    if (next !== current) element.setAttribute(attribute, next);
  }
}
