export const GERMAN_COPY_PAIRS: [string, string][] = [
  ["Luxury human hair extensions crafted for women who refuse compromise. Sourced from the world's finest suppliers, installed by Berlin's most trusted specialists.", "Luxuriöse Echthaar-Extensions für Frauen, die keine Kompromisse eingehen. Von den besten Lieferanten weltweit, installiert von Berlins renommiertesten Spezialisten."],
  ["Luxury extensions crafted for women who refuse compromise.", "Luxuriöse Extensions für Frauen, die keine Kompromisse eingehen."],
  ["Luxury Hair. Premium Quality. Every Strand Designed Just For You.", "Luxuriöses Haar. Premium-Qualität. Jede Strähne für dich perfektioniert."],
  ["Luxury Hair. Premium Quality. Designed for You.", "Luxuriöses Haar. Premium-Qualität. Für dich gemacht."],
  ["Stay connected with OlivHairSupply Club.", "Bleib immer auf dem Laufenden mit dem OlivHairSupply Club."],
  ["Stay connected with Olivhairsupply Club.", "Bleib immer auf dem Laufenden mit dem OlivHairSupply Club."],
  ["Worldwide Shipping — Free Over €200", "Weltweiter Versand – kostenlos ab 200 €"],
  ["Worldwide Shipping â€” Free Over â‚¬200", "Weltweiter Versand – kostenlos ab 200 €"],
  ["Free EU shipping on orders over €200", "Kostenloser EU-Versand ab 200 €"],
  ["Free EU Shipping Over €200", "Kostenloser EU-Versand ab 200 €"],
  ["FREE EU SHIPPING OVER €200", "KOSTENLOSER EU-VERSAND AB 200 €"],
  ["Free EU shipping on orders over â‚¬200", "Kostenloser EU-Versand ab 200 €"],
  ["Free EU Shipping Over â‚¬200", "Kostenloser EU-Versand ab 200 €"],
  ["FREE EU SHIPPING OVER â‚¬200", "KOSTENLOSER EU-VERSAND AB 200 €"],
  ["FREE EU SHIPPING", "KOSTENLOSER EU-VERSAND"],
  ["Free EU Shipping", "Kostenloser EU-Versand"],
  ["100% Human Hair", "100 % Echthaar"],
  ["100% HUMAN HAIR", "100 % ECHTHAAR"],
  ["Expert Colour Matching", "Professionelle Farbberatung"],
  ["EXPERT COLOUR MATCHING", "PROFESSIONELLE FARBBERATUNG"],
  ["Worldwide Delivery", "Weltweite Lieferung"],
  ["WORLDWIDE DELIVERY", "WELTWEITE LIEFERUNG"],
  ["Berlin In-Store Experience", "Berlin Salon-Erlebnis"],
  ["BERLIN IN-STORE EXPERIENCE", "BERLIN SALON-ERLEBNIS"],
  ["BiziLuxe Collection", "BiziLuxe Kollektion"],
  ["Shop BiziLuxe Hair", "BiziLuxe entdecken"],
  ["SHOP BIZILUXE HAIR", "BIZILUXE ENTDECKEN"],
  ["SHOP BIZILUXE", "BIZILUXE ENTDECKEN"],
  ["Book an Appointment", "Termin buchen"],
  ["Book Appointment", "Termin buchen"],
  ["BOOK APPOINTMENT", "TERMIN BUCHEN"],
  ["Premium Hair.", "Premium-Haar."],
  ["Confidence.", "Eleganz."],
  ["Effortless", "Mühelose"],
  ["Become an Affiliate →", "Affiliate-Partner werden →"],
  ["Become an Affiliate â†’", "Affiliate-Partner werden →"],
  ["Become an Affiliate", "Affiliate werden"],
  ["Affiliate Programme", "Affiliate-Programm"],
  ["Affiliate Program", "Affiliate-Programm"],
  ["Social Responsibility", "Soziale Verantwortung"],
  ["Track Order", "Bestellung verfolgen"],
  ["Stay Connected", "Verbunden bleiben"],
  ["STAY CONNECTED", "VERBUNDEN BLEIBEN"],
  ["Contact Us", "Kontakt"],
  ["Our Story", "Unsere Geschichte"],
  ["Sustainability", "Nachhaltigkeit"],
  ["Wholesale", "Großhandel"],
  ["Training", "Schulungen"],
  ["Appointment", "Termin buchen"],
  ["Careers", "Karriere"],
  ["Journal", "Magazin"],
  ["Returns", "Rücksendungen"],
  ["Shipping", "Versand"],
  ["Rentals", "Clip-in-Verleih"],
  ["Services", "Dienstleistungen"],
  ["Affiliate", "Affiliate"],
  ["About", "Über uns"],
  ["ABOUT", "ÜBER UNS"],
  ["Press", "Presse"],
  ["More", "Mehr"],
  ["MORE", "MEHR"],
  ["Help", "Hilfe"],
  ["HELP", "HILFE"],
  ["Home", "Startseite"],
  ["Shop", "Shop"],
  ["FAQ", "FAQ"],
  ["Language & Currency", "Sprache & Währung"],
  ["Language", "Sprache"],
  ["Currency", "Währung"],
  ["Search", "Suche"],
  ["Log in", "Anmelden"],
  ["Account", "Konto"],
  ["Cart", "Warenkorb"],
  ["Cart (0)", "Warenkorb (0)"],
  ["Open menu", "Menü öffnen"],
  ["Close menu", "Menü schließen"],
  ["First name", "Vorname"],
  ["Email address", "E-Mail-Adresse"],
  ["Subscribe", "Abonnieren"],
  ["Subscribe →", "Abonnieren →"],
  ["Subscribe &rarr;", "Abonnieren &rarr;"],
  ["No spam. Unsubscribe at any time.", "Kein Spam. Du kannst dich jederzeit abmelden."],
  ["Privacy Policy", "Datenschutzerklärung"],
  ["Terms and Conditions", "Allgemeine Geschäftsbedingungen"],
  ["All rights reserved.", "Alle Rechte vorbehalten."],
  ["Partner With OlivHairSupply", "Partner von OlivHairSupply werden"],
  ["Partner With ", "Partner von "],
  ["Partner With", "Partner von"],
  ["Become a wholesaler", "Werde Großhandelspartner"],
  ["Become a Wholesaler", "Werde Großhandelspartner"],
  ["Log Into Wholesale Shop", "Zum Großhandelsshop anmelden"],
  ["Log into Wholesale Shop", "Zum Großhandelsshop anmelden"],
  ["BiziLuxe Clip-In Collection", "BiziLuxe Clip-in-Kollektion"],
  ["Book Rental Consultation", "Beratung zur Anmietung buchen"],
  ["Speak to Our Team", "Unser Team kontaktieren"],
  ["Book Your Consultation", "Beratung buchen"],
  ["Luxury Hair ", "Luxuriöse Extensions zum "],
  ["Luxury Hair", "Luxuriöse Extensions"],
  ["Rentals.", "Mieten."],
  ["Our Services", "Unsere Dienstleistungen"],
  ["Tailored to You.", "für dein perfektes Haar."],
  ["Services ", "Individuelle Lösungen "],
  ["Book Training Consultation", "Beratungsgespräch buchen"],
  ["Become professionally ", "Werde professionell "],
  ["Become professionally", "Werde professionell"],
  ["Certified.", "zertifiziert."],
  ["Enroll Now", "Jetzt anmelden"],
  ["Berlin, Est. 2016", "Berlin, gegründet 2016"],
  ["Born from", "Aus Leidenschaft"],
  ["a passion", "entstanden"],
  ["The BiziLuxe Edit", "Die BiziLuxe Kollektion"],
  ["The BiziLuxe", "Die BiziLuxe"],
  ["Edit", "Kollektion"],
  ["100 %Cuticle-Aligned Human Hair", "100 % Echthaar mit intakter Schuppenschicht"],
  ["100% Cuticle-Aligned Human Hair", "100 % Echthaar mit intakter Schuppenschicht"],
  ["Cuticle-Aligned Human Hair", "Echthaar mit intakter Schuppenschicht"],
  ["6Collections", "6 Kollektionen"],
  ["6 Collections", "6 Kollektionen"],
  ["Collections", "Kollektionen"],
  ["Collection", "Kollektion"],
  ["EUWorldwide Shipping", "Weltweiter Versand"],
  ["EU Worldwide Shipping", "Weltweiter Versand"],
  ["Free ShippingOn orders over €200", "Kostenloser Versand ab 200 €"],
  ["Free Shipping On orders over €200", "Kostenloser Versand ab 200 €"],
  ["Free ShippingOn orders over â‚¬200", "Kostenloser Versand ab 200 €"],
  ["Free Shipping On orders over â‚¬200", "Kostenloser Versand ab 200 €"],
  ["On orders over €200", "Ab Bestellungen über 200 €"],
  ["On orders over â‚¬200", "Ab Bestellungen über 200 €"],
  ["14 Day ReturnsUnused sealed products", "14 Tage Rückgaberecht für unbenutzte und versiegelte Produkte"],
  ["14 Day Returns", "14 Tage Rückgaberecht"],
  ["Unused sealed products", "Für unbenutzte und versiegelte Produkte"],
  ["Expert GuidanceBook a free consultation", "Persönliche Beratung – kostenlose Beratung buchen"],
  ["Expert Guidance", "Persönliche Beratung"],
  ["Book a free consultation", "Kostenlose Beratung buchen"],
  ["EthicallySourcedQuality guaranteed", "Ethisch bezogen – garantierte Qualität"],
  ["Ethically SourcedQuality guaranteed", "Ethisch bezogen – garantierte Qualität"],
  ["Ethically Sourced", "Ethisch bezogen"],
  ["Quality guaranteed", "Garantierte Qualität"],
];

const TRANSLATABLE_ATTRIBUTES = ["aria-label", "title", "placeholder", "alt"] as const;

type ManualPageOverride = {
  selector: string;
  text?: string;
  html?: string;
  attr?: (typeof TRANSLATABLE_ATTRIBUTES)[number];
  index?: number;
};

const HOME_PAGE_DE_OVERRIDES: ManualPageOverride[] = [
  { selector: ".ohp-collections-header .ohp-eyebrow", text: "BiziLuxe Kollektion" },
  { selector: ".ohp-collections-header .ohp-col-title", html: "Nach Kategorie <em>entdecken</em>" },
  { selector: '.ohp-col-card[href="/collections/bizihair-extensions"] .ohp-col-tag', text: "BiziHair Haarverlängerungen" },
  { selector: '.ohp-col-card[href="/shop"] .ohp-col-tag', text: "BiziLuxe Hair" },
  { selector: '.ohp-col-card[href="/collections/biziluxe-tools"] .ohp-col-tag', text: "BiziLuxe Tools" },
  { selector: '.ohp-col-card[href="/collections/biziluxe-accessories"] .ohp-col-tag', text: "BiziLuxe Accessoires" },
  { selector: ".ohp-col-cta", text: "Entdecken" },

  { selector: ".ohp-featured-header .ohp-eyebrow", text: "Neuheiten" },
  { selector: ".ohp-featured-header .ohp-title", text: "Bestseller" },
  { selector: ".ohp-product-name", text: "BiziLuxe Produkt" },
  { selector: ".ohp-product-price", text: "Ab €0.00" },
  { selector: ".ohp-product-btn", text: "Jetzt kaufen" },
  { selector: ".ohp-featured-footer .ohp-btn-outline-dark", text: "Alle Produkte ansehen" },

  { selector: ".ohp-brand .ohp-eyebrow", text: "Unser Anspruch" },
  { selector: ".ohp-brand-quote", text: "Haare, die für sich selbst sprechen." },
  { selector: ".ohp-brand .ohp-body", index: 0, text: "BiziLuxe Haar ist für Frauen gemacht, die wissen: Qualität ist kein Luxus — sie ist Standard. Jedes Haar wird ausgewählt, jede Struktur wird beachtet, und jedes Produkt ist entwickelt, um sich zu bewegen, sich anzufühlen und genau wie echtes Premium-Haar zu funktionieren." },
  { selector: ".ohp-brand .ohp-body", index: 1, text: "Bei OlivHairSupply machen wir keine Kompromisse. Von unseren Berlin-Salons bis zur internationalen Lieferung — der Standard bleibt gleich." },
  { selector: ".ohp-brand .ohp-btn-outline-dark", text: "Unsere Geschichte" },

  { selector: ".ohp-block-warm .ohp-eyebrow", text: "OlivHairSupply Academy" },
  { selector: ".ohp-block-warm .ohp-title", text: "Werde zertifizierte Spezialistin." },
  { selector: ".ohp-block-warm .ohp-body", index: 0, text: "Lerne professionelle Einbautechniken, beherrsche das BiziLuxe System und baue deine Karriere im Premium-Bereich der Haarindustrie auf. Unsere Schulungsprogramme sind für Ehrgeiz gemacht." },
  { selector: ".ohp-block-warm .ohp-body", index: 1, text: "Drei Programme verfügbar — Foundation, Advanced und Master Business." },
  { selector: ".ohp-block-warm .ohp-btn-outline-dark", text: "Zur Schulung" },

  { selector: ".ohp-appointment .ohp-appt-eyebrow", text: "Dein Termin bei uns" },
  { selector: ".ohp-appointment .ohp-appt-title", text: "Dein Luxus-Erlebnis wartet." },
  { selector: ".ohp-appointment .ohp-appt-sub", text: "Besuche einen unserer Berlin-Salons für eine Premium-Haarverlängerung oder ein Premium-Styling. Fachleute, Luxusprodukte und ein Ergebnis, das spricht. Buche deinen Termin noch heute." },
  { selector: ".ohp-appointment .ohp-btn-ivory", text: "Termin vereinbaren" },
  { selector: ".ohp-appointment .ohp-btn-ivory-out", text: "Services ansehen" },

  { selector: ".ohp-block-ivory .ohp-eyebrow", text: "Clip-in-Verleih" },
  { selector: ".ohp-block-ivory .ohp-title", text: "Luxus-Haar für jeden Anlass." },
  { selector: ".ohp-block-ivory .ohp-body", index: 0, text: "Noch nicht kaufbereit? Unser Clip-in-Verleih gibt dir Zugang zu BiziLuxe Haarteilen für Events, Shoots oder besondere Anlässe — zu einem Bruchteil des Preises." },
  { selector: ".ohp-block-ivory .ohp-body", index: 1, text: "Verfügbar für Kunden in Berlin und ausgewählten Standorten. Kontaktiere uns, um die Verfügbarkeit für dein Event zu prüfen." },
  { selector: ".ohp-block-ivory .ohp-btn-outline-dark", text: "Clip-in-Verleih entdecken" },
  { selector: ".ohp-rental-image", attr: "alt", text: "OlivHairSupply Clip-in-Verleih" },

  { selector: ".ohp-testimonials-header .ohp-eyebrow", text: "Kunden-Geschichten" },
  { selector: ".ohp-testimonials-title", text: "Das sagen unsere Kunden" },
  { selector: ".ohp-testimonial-quote", index: 0, text: "Die Qualität von BiziLuxe Haar ist einfach unvergleichlich. Es verschmilzt perfekt und hält so viel länger als alles, das ich vorher getestet habe." },
  { selector: ".ohp-testimonial-quote", index: 1, text: "Mein Termin war vom Anfang bis zum Ende purer Luxus. Das Team bei OlivHairSupply versteht wirklich, was Premium-Service bedeutet." },
  { selector: ".ohp-testimonial-quote", index: 2, text: "Das Advanced Training hat meine Karriere komplett transformiert. Jetzt bediene ich eine Premium-Kundschaft und kann meine Arbeit fair bezahlen." },
  { selector: ".ohp-testimonial-loc", index: 0, text: "Berlin, Deutschland" },

  { selector: ".ohp-instagram-header .ohp-eyebrow", text: "Folge unserer Story" },
  { selector: ".ohp-instagram-footer .ohp-btn-outline-dark", text: "Auf Instagram folgen" },

  { selector: ".ohs-nl-section-eyebrow", text: "Das OlivHairSupply Edit" },
  { selector: ".ohs-nl-section-title", text: "Tritt dem OlivHairSupply Edit bei" },
  { selector: ".ohs-nl-section-sub", text: "Exklusive Drops, professionelle Haar-Tipps und Luxus-Updates direkt in dein Postfach." },
  { selector: '.ohs-nl-section-input[name="contact[first_name]"]', attr: "placeholder", text: "Vorname" },
  { selector: '.ohs-nl-section-input[name="contact[email]"]', attr: "placeholder", text: "E-Mail-Adresse" },
  { selector: ".ohs-nl-section-btn", text: "Anmelden →" },
  { selector: ".ohs-nl-section-note", text: "Kein Spam. Abmeldung jederzeit möglich." },

  { selector: ".ohp-trust .ohp-trust-text", index: 0, text: "100% Echthaar" },
  { selector: ".ohp-trust .ohp-trust-text", index: 1, text: "Versandkostenfrei EU ab €200" },
  { selector: ".ohp-trust .ohp-trust-text", index: 2, text: "Professionelle Farbberatung" },
  { selector: ".ohp-trust .ohp-trust-text", index: 3, text: "Weltweiter Versand" },
  { selector: ".ohs-trust .ohs-trust-text", index: 0, text: "100% Echthaar" },
  { selector: ".ohs-trust .ohs-trust-text", index: 1, text: "Versandkostenfrei EU ab €200" },
  { selector: ".ohs-trust .ohs-trust-text", index: 2, text: "Professionelle Farbberatung" },
  { selector: ".ohs-trust .ohs-trust-text", index: 3, text: "Weltweiter Versand" },

  { selector: ".oab-hero-eyebrow", text: "Berlin, seit 2016" },
  { selector: ".oab-hero-title", html: "Aus Leidenschaft <em>entstanden</em>" },
  { selector: ".oab-btn-hero-gold", text: "Karriere" },
  { selector: ".oab-btn-hero-dark", text: "Termin vereinbaren" },

  { selector: ".oab-story-text .oab-eyebrow", text: "Unsere Geschichte" },
  { selector: ".oab-story-title", html: "Von einem Stuhl<br>zu einer <em>Bewegung.</em>" },
  { selector: ".oab-story-text .oab-body", index: 0, text: "OlivHairSupply ist aus echter Erfahrung entstanden, nicht aus Theorie." },
  { selector: ".oab-story-text .oab-body", index: 1, text: "Nach Jahren praktischer Arbeit als Spezialistinnen für Haarverlängerungen, im Verkauf und in der Anwendung für unterschiedlichste Kundinnen, haben wir immer wieder dasselbe Problem gesehen: schwankende Haarqualität, unzuverlässige Tools und Produkte, die professionellen Ansprüchen einfach nicht gerecht wurden." },
  { selector: ".oab-story-text .oab-body", index: 2, text: "Statt das als Standard zu akzeptieren, haben wir uns entschieden, ihn neu zu definieren." },
  { selector: ".oab-story-text .oab-body", index: 3, text: "Durch kontinuierliches Kundenfeedback und tägliche Praxiserfahrung haben wir unser Verständnis dafür geschärft, was hochwertiges Haar wirklich ausmacht — von Struktur und Langlebigkeit bis zu Tragekomfort und Performance. Daraus entstanden Produkte, die den Erwartungen von Profis und Kundinnen gleichermaßen entsprechen." },
  { selector: ".oab-story-text .oab-body", index: 4, text: "Aber unsere Reise endete nicht beim Haar." },
  { selector: ".oab-story-text .oab-body", index: 5, text: "Als Spezialistinnen wissen wir aus eigener Erfahrung, wie schwer es ist, Tools und Geräte zu finden, die langlebig, effizient und wirklich für den Salonalltag gemacht sind. Viele Produkte am Markt halten langfristig nicht, was sie versprechen." },
  { selector: ".oab-story-text .oab-body", index: 6, text: "Deshalb haben wir BiziLuxe eingeführt: eine Premium-Linie professioneller Tools, Accessoires und Haarlösungen, sorgfältig recherchiert und ausgewählt für die Anforderungen moderner Hair Artists. Jedes Produkt wird mit Fokus auf Haltbarkeit, Präzision und einfache Anwendung ausgewählt." },
  { selector: ".oab-story-text .oab-body", index: 7, text: "Heute ist OlivHairSupply eine zentrale Adresse für hochwertiges Haar, professionelle Tools und ausgewählte Accessoires — aufgebaut auf Fachwissen, geformt durch echte Erfahrung und getragen von dem Anspruch, bessere Lösungen für Profis und Kundinnen zu schaffen." },
  { selector: ".oab-story-text .oab-body", index: 8, html: "Wir verkaufen nicht einfach Produkte.<br>Wir bieten Lösungen, denen wir vertrauen, die wir selbst nutzen und hinter denen wir stehen." },
  { selector: ".oab-story-text .oab-btn-dark", text: "Besuche uns" },

  { selector: ".oab-values > .oab-eyebrow", text: "Wofür wir stehen" },
  { selector: ".oab-values-title", html: "Unsere vier <em>Säulen.</em>" },
  { selector: ".oab-val-title", index: 0, text: "Qualität ohne Kompromisse" },
  { selector: ".oab-val-text", index: 0, text: "Jede Strähne ist 100% Remy-Echthaar, ethisch bezogen von vertrauenswürdigen Partnern. Wir prüfen jede Charge, bevor sie eine Kundin erreicht." },
  { selector: ".oab-val-title", index: 1, text: "Expertise, der du vertrauen kannst" },
  { selector: ".oab-val-text", index: 1, text: "Unsere Stylistinnen sind zertifiziert, intern geschult und leidenschaftlich in ihrem Handwerk. Präzision ist nicht nur unser Standard — sie ist unsere Identität." },
  { selector: ".oab-val-title", index: 2, text: "Wirklich maßgeschneidert" },
  { selector: ".oab-val-text", index: 2, text: "Kein Haar ist wie das andere. Jede Beratung, jede Einarbeitung und jede Pflegeempfehlung wird auf dich und deinen Lebensstil abgestimmt." },
  { selector: ".oab-val-title", index: 3, text: "Community und Selbstbewusstsein" },
  { selector: ".oab-val-text", index: 3, text: "OlivHairSupply ist mehr als ein Salon. Wir sind eine Community von Frauen, die daran glauben: Sich schön zu fühlen ist kein Luxus — es ist ein Recht." },

  { selector: ".oab-tl-header .oab-eyebrow", text: "Unser Weg" },
  { selector: ".oab-tl-title", html: "Wachsen mit <em>Anspruch.</em>" },
  { selector: ".oab-tl-name", index: 0, text: "Die Gründung" },
  { selector: ".oab-tl-body", index: 0, text: "OlivHairSupply startet als Online-Shop mit klarem Fokus: hochwertige Haarverlängerungen für Kundinnen in ganz Deutschland zu sourcen und verfügbar zu machen." },
  { selector: ".oab-tl-name", index: 1, text: "Online-Shop Launch" },
  { selector: ".oab-tl-body", index: 1, text: "Wir launchen olivhairsupply.de und bringen unsere kuratierten BiziHair- und Olivhairlux-Kollektionen zu Kundinnen in ganz Europa." },
  { selector: ".oab-tl-name", index: 2, text: "Eröffnung in Schöneberg" },
  { selector: ".oab-tl-body", index: 2, text: "Der erste Salon- und Retail-Standort in Berlin-Schöneberg entsteht auf 60 qm — mit Produktverkauf und zwei Plätzen für Haarverlängerungen." },
  { selector: ".oab-tl-name", index: 3, text: "Expansion und Wachstum" },
  { selector: ".oab-tl-body", index: 3, text: "Aufgrund steigender Nachfrage erweitert sich der Standort auf 100 qm mit vier Plätzen für Haarverlängerungen." },
  { selector: ".oab-tl-name", index: 4, text: "Planung und Strategie" },
  { selector: ".oab-tl-body", index: 4, text: "Ein Jahr im Zeichen langfristiger Expansion, Struktur und Vorbereitung." },
  { selector: ".oab-tl-name", index: 5, text: "Expansion am Kurfürstendamm" },
  { selector: ".oab-tl-body", index: 5, text: "Der zweite Standort wird in einer der renommiertesten Retail-Lagen Berlins gesichert." },
  { selector: ".oab-badge.coming", text: "Demnächst" },
  { selector: ".oab-tl-name", index: 6, text: "Flagship Launch (290 qm)" },
  { selector: ".oab-tl-body", index: 6, text: "Full-Service Flagship Store mit Premium-Haar, professionellen Tools, Geräten und B2B-Zugang." },
  { selector: ".oab-btn-sm", text: "Als Erste erfahren" },
  { selector: ".oab-btn-sm-out", text: "Kontakt aufnehmen" },

  { selector: ".oab-exp-title", html: "Wir wachsen in Berlin.<br><em>Der zweite Standort kommt.</em>" },
  { selector: ".oab-exp-body", text: "Unser zweiter Standort ist auf dem Weg. Mehr Raum. Mehr Stylistinnen. Mehr von dem OlivHairSupply Erlebnis, das du liebst. Trag dich in unseren Newsletter ein und erfahre die Neuigkeiten als Erste." },
  { selector: ".oab-btn-ivory", text: "Zur Warteliste" },
  { selector: ".oab-btn-ivory-out", text: "Kontakt" },

  { selector: ".oab-team-header .oab-eyebrow", text: "Die Menschen hinter OlivHairSupply" },
  { selector: ".oab-team-title", html: "Lerne unsere <em>Hair Specialists</em> kennen" },
  { selector: ".oab-team-intro", text: "Bei OlivHairSupply folgt jeder Service einem klar definierten Standard aus Qualität, Präzision und Beständigkeit. Unser Spezialistinnen-Team ist geschult, damit jede Kundin ein nahtloses, individuell abgestimmtes Ergebnis erhält — unabhängig von der Stylistin." },
  { selector: ".oab-team-role", index: 0, text: "Gründerin und Creative Director" },
  { selector: ".oab-team-specialty", index: 0, text: "Advanced Colour Blending, alle Extension-Methoden und Stylistinnen-Training" },
  { selector: ".oab-team-bio", index: 0, text: "Setzt den OlivHairSupply Standard und verantwortet Qualität, Ausbildung und Produktentwicklung an allen Standorten. Termine nur begrenzt verfügbar." },
  { selector: ".oab-team-role", index: 1, text: "Extension- und Perückenspezialistin" },
  { selector: ".oab-team-specialty", index: 1, text: "Weaving, Tape-ins, Full Weaves, Perückeninstallationen und Braiding" },
  { selector: ".oab-team-bio", index: 1, text: "Mit umfassender Praxiserfahrung liefert sie vielseitige, gepflegte und langanhaltende Ergebnisse." },
  { selector: ".oab-team-role", index: 2, text: "Client Experience und Senior Extension Specialist" },
  { selector: ".oab-team-specialty", index: 2, text: "Bondings, Tape-ins und präzise Farbabstimmung" },
  { selector: ".oab-team-bio", index: 2, text: "Mit über 15 Jahren Erfahrung bietet sie fachkundige Beratung und perfektes Matching." },
  { selector: ".oab-team-role", index: 3, text: "Senior Extension Specialist" },
  { selector: ".oab-team-specialty", index: 3, text: "Weaving, Brazilian Knots, Tape-ins, Keratin-Bondings und Braiding" },
  { selector: ".oab-team-bio", index: 3, text: "Nach OlivHairSupply Standards geschult und spezialisiert auf nahtlose, natürliche Ergebnisse." },
  { selector: ".oab-team-role", index: 4, text: "Senior Braiding und Extension Specialist" },
  { selector: ".oab-team-specialty", index: 4, text: "Braids, Cornrows, Weaving und Brazilian Knots" },
  { selector: ".oab-team-bio", index: 4, text: "Mit über 15 Jahren Erfahrung, bekannt für Präzision, saubere Finishes und hohen Kundenkomfort." },

  { selector: ".otr-hero-img", attr: "alt", text: "OlivHairSupply Academy" },
  { selector: ".otr-eyebrow", text: "OlivHairSupply Academy" },
  { selector: ".otr-hero-title", html: "Werde professionell <em>zertifiziert.</em>" },
  { selector: ".otrn-btn-gold", text: "Jetzt anmelden" },
  { selector: ".otrn-btn-dark", text: "Beratung zur Schulung buchen" },

  { selector: ".otrg-img-label", index: 0, text: "Präzises Arbeiten" },
  { selector: ".otrg-img-title", index: 0, html: "Expertinnen-Hände.<br><em>Jedes Detail.</em>" },
  { selector: ".otrg-img-label", index: 1, text: "Styling & Finish" },
  { selector: ".otrg-img-title", index: 1, html: "Makellos.<br><em>Jedes Mal.</em>" },

  { selector: ".otr-value .otr-section-eyebrow", text: "Warum diese Schulung anders ist" },
  { selector: ".otr-value .otr-section-title", html: "Mehr als Training.<br><em>Ein Business-Upgrade.</em>" },
  { selector: ".otr-value-lead", text: "Hier geht es nicht nur darum, Haare zu lernen." },
  { selector: ".otr-value-body", text: "In der OlivHairSupply Academy lernst du, Premium-Ergebnisse für Kundinnen zu liefern, mit luxuriösem BiziLuxe Haar zu arbeiten und eine Marke aufzubauen, die den Preis verdient, den deine Arbeit wert ist." },
  { selector: ".otr-value-point", index: 0, text: "Premium-Ergebnisse liefern, die Empfehlungen auslösen" },
  { selector: ".otr-value-point", index: 1, text: "Sicher mit luxuriösen BiziLuxe Haarsystemen arbeiten" },
  { selector: ".otr-value-point", index: 2, text: "Deine Services klar und selbstbewusst kalkulieren" },
  { selector: ".otr-value-point", index: 3, text: "Eine nachhaltige und profitable Beauty-Marke aufbauen" },
  { selector: ".otr-value-img-ph span", text: "Schulungsbild" },

  { selector: ".otr-programmes-header .otr-section-eyebrow", text: "Wähle dein Programm" },
  { selector: ".otr-programmes-header .otr-section-title", html: "Investiere in deine <em>Zukunft</em>" },
  { selector: ".otr-programmes-header .otr-section-sub", text: "Drei strukturierte Programme, die dich vom Fundament bis zur Meisterschaft führen." },
  { selector: ".otr-prog-badge", index: 1, text: "Am beliebtesten" },
  { selector: ".otr-prog-name", index: 0, text: "Beginner Foundation" },
  { selector: ".otr-prog-duration", index: 0, text: "1 Tag Intensiv" },
  { selector: ".otr-prog-price", index: 0, text: "Ab €500" },
  { selector: ".otr-prog-price", index: 1, text: "Ab €1200" },
  { selector: ".otr-prog-price", index: 2, text: "Ab €2500" },
  { selector: ".otr-prog-price-label", text: "Alle Materialien inklusive" },
  { selector: ".otr-prog-desc", index: 0, text: "Starte deine Reise in die Premium-Haarverlängerung mit starken Grundlagen, fachlicher Begleitung und dem Selbstvertrauen, ab Tag eins Ergebnisse zu liefern." },
  { selector: ".otr-prog-desc", index: 1, text: "Meistere nahtlose Einarbeitungen über mehrere Systeme hinweg und hebe deinen professionellen Standard auf das Niveau des Luxusmarktes." },
  { selector: ".otr-prog-desc", index: 2, text: "Für Profis, die bereit sind, eine Luxusmarke aufzubauen und ein einkommensstarkes Business mit Premium-Kundinnen zu entwickeln." },
  { selector: ".otr-prog-includes li", index: 0, text: "Einführung in Haarverlängerungen" },
  { selector: ".otr-prog-includes li", index: 1, text: "Grundlegende Extension-Methoden" },
  { selector: ".otr-prog-includes li", index: 2, text: "Beratungskompetenz für Kundinnen" },
  { selector: ".otr-prog-includes li", index: 3, text: "Pflegeempfehlung und Systeme" },
  { selector: ".otr-prog-includes li", index: 4, text: "Tape-ins meistern" },
  { selector: ".otr-prog-includes li", index: 5, text: "Hand-tied Wefts" },
  { selector: ".otr-prog-includes li", index: 6, text: "Blending und Styling" },
  { selector: ".otr-prog-includes li", index: 7, text: "Fortgeschrittene Extension-Methoden" },
  { selector: ".otr-prog-includes li", index: 8, text: "Premium-Kundenerlebnis" },
  { selector: ".otr-prog-includes li", index: 9, text: "Preisstrategie" },
  { selector: ".otr-prog-includes li", index: 10, text: "Branding und Positionierung" },
  { selector: ".otr-prog-includes li", index: 11, text: "Kundengewinnung und Kundenbindung" },
  { selector: ".otr-prog-cta", text: "Jetzt anmelden" },

  { selector: ".otr-master-header .otr-section-eyebrow", text: "Curriculum" },
  { selector: ".otr-master-header .otr-section-title", html: "Was du <em>meisterst</em>" },
  { selector: ".otr-master-header .otr-section-sub", text: "Jedes Modul ist darauf ausgelegt, dich zu einer vollständigen, hochwertigen Fachperson zu entwickeln." },
  { selector: ".otr-master-title", index: 0, text: "Haar-Sourcing und Qualitätskontrolle" },
  { selector: ".otr-master-text", index: 0, text: "Verstehe, was Premium-Haar ausmacht und wie du Qualität in jeder Phase bewertest." },
  { selector: ".otr-master-title", index: 1, text: "Präzise Einarbeitung" },
  { selector: ".otr-master-text", index: 1, text: "Meistere die technischen Fähigkeiten für makellose, langanhaltende Einarbeitungen." },
  { selector: ".otr-master-title", index: 2, text: "Farbabstimmung und Blending" },
  { selector: ".otr-master-text", index: 2, text: "Schule dein Auge, um natürliche Farbtöne nahtlos abzustimmen und zu verblenden." },
  { selector: ".otr-master-title", index: 3, text: "Styling und Finish" },
  { selector: ".otr-master-text", index: 3, text: "Liefere Styling-Ergebnisse auf Editorial-Niveau, die das gesamte Kundenerlebnis aufwerten." },
  { selector: ".otr-master-title", index: 4, text: "Kundenberatung" },
  { selector: ".otr-master-text", index: 4, text: "Führe sichere, professionelle Beratungen, die Vertrauen schaffen und Buchungen sichern." },
  { selector: ".otr-master-title", index: 5, text: "Pflegeempfehlung" },
  { selector: ".otr-master-text", index: 5, text: "Gib jeder Kundin einen vollständigen Pflegeplan, der deine Arbeit schützt und Loyalität aufbaut." },
  { selector: ".otr-master-title", index: 6, text: "Preisgestaltung und Profitabilität" },
  { selector: ".otr-master-text", index: 6, text: "Lerne, deine Services so zu kalkulieren, dass sie deinen Wert widerspiegeln und nachhaltiges Einkommen schaffen." },
  { selector: ".otr-master-title", index: 7, text: "Business- und Markenaufbau" },
  { selector: ".otr-master-text", index: 7, text: "Positioniere dich als Luxus-Spezialistin und ziehe Kundinnen an, die deine Arbeit wertschätzen." },

  { selector: ".otr-who .otr-section-eyebrow", text: "Ist das für dich?" },
  { selector: ".otr-who .otr-section-title", html: "Gemacht für <em>Ehrgeiz.</em>" },
  { selector: ".otr-who .otr-section-sub", text: "Unsere Programme sind für alle, die ernsthaft eine Karriere im Premium-Bereich der Haarindustrie aufbauen wollen." },

  { selector: ".otr-cert .otr-section-eyebrow", text: "Offizielle Anerkennung" },
  { selector: ".otr-cert-title", html: "Erhalte deine <em>Zertifizierung</em>" },
  { selector: ".otr-cert-text", index: 0, text: "Nach Abschluss deines Programms erhältst du eine offizielle OlivHairSupply Zertifizierung, die deine Expertise in luxuriösen Haarsystemen und Premium-Service bestätigt." },
  { selector: ".otr-cert-text", index: 1, text: "Dein Zertifikat ist ein Qualitätszeichen. Es zeigt Kundinnen und Arbeitgebern, dass du nach dem OlivHairSupply Standard ausgebildet wurdest." },
  { selector: ".otr-cert .otr-btn-gold", text: "Jetzt anmelden" },
  { selector: ".otr-cert-badge-sub", text: "Zertifizierte Spezialistin" },
  { selector: ".otr-cert-badge-text", text: "Verliehen nach erfolgreichem Abschluss des OlivHairSupply Academy Programms." },

  { selector: ".otr-exp-header .otr-section-eyebrow", text: "Das Erlebnis" },
  { selector: ".otr-exp-header .otr-section-title", html: "Training, das sich <em>anders anfühlt.</em>" },
  { selector: ".otr-exp-title", index: 0, text: "Kleine Gruppen" },
  { selector: ".otr-exp-text", index: 0, text: "Intime Gruppen sorgen dafür, dass jede Teilnehmerin direkte Aufmerksamkeit, persönliches Feedback und echte Entwicklung erhält." },
  { selector: ".otr-exp-title", index: 1, text: "Praxisnahes Training" },
  { selector: ".otr-exp-text", index: 1, text: "Jede Session ist praktisch. Du arbeitest mit echtem Haar, echten Kundinnen und realen Szenarien vom ersten Tag an." },
  { selector: ".otr-exp-title", index: 2, text: "Direkte Expertenbegleitung" },
  { selector: ".otr-exp-text", index: 2, text: "Lerne direkt von OlivHairSupply Spezialistinnen mit jahrelanger Erfahrung in luxuriöser Einarbeitung und Business." },
  { selector: ".otr-exp-title", index: 3, text: "Reale Kundenszenarien" },
  { selector: ".otr-exp-text", index: 3, text: "Trainiere unter Bedingungen, die das echte Premium-Kundenerlebnis widerspiegeln — von der Beratung bis zum finalen Ergebnis." },

  { selector: ".otr-cta-eyebrow", text: "Dein nächster Schritt" },
  { selector: ".otr-cta-title", html: "Starte deine<br><em>Luxus-Karriere</em>" },
  { selector: ".otr-cta-sub", text: "Die Plätze sind begrenzt. Sichere dir heute deinen Platz und beginne deinen Weg zur zertifizierten Luxus-Haar-Spezialistin." },
  { selector: ".otr-btn-cta-primary", text: "Jetzt bewerben" },
  { selector: ".otr-btn-cta-outline", text: "Beratung zur Schulung buchen" },

  { selector: "#otrg-apply-close", attr: "aria-label", text: "Schließen" },
  { selector: "#otrg-login-close", attr: "aria-label", text: "Schließen" },
  { selector: "#otrg-apply-overlay .otrg-modal-eyebrow", text: "Schulungsbewerbung" },
  { selector: "#otrg-apply-overlay .otrg-modal-title", html: "Für die <em>Zertifizierung</em> bewerben" },
  { selector: "#otrg-apply-overlay .otrg-modal-sub", text: "Fülle das Formular aus. Unser Team prüft jede Bewerbung persönlich und meldet sich innerhalb von 3 bis 5 Werktagen bei dir." },
  { selector: ".otrg-form-label", index: 0, text: "Vollständiger Name" },
  { selector: ".otrg-form-label", index: 1, text: "E-Mail-Adresse" },
  { selector: ".otrg-form-label", index: 2, text: "Telefonnummer" },
  { selector: ".otrg-form-label", index: 3, text: "Gewünschtes Programm" },
  { selector: ".otrg-form-label", index: 4, text: "Aktuelles Erfahrungslevel" },
  { selector: ".otrg-form-label", index: 5, text: "Warum möchtest du bei uns lernen?" },
  { selector: "#otrg-name", attr: "placeholder", text: "Dein vollständiger Name" },
  { selector: "#otrg-programme option", index: 0, text: "Programm auswählen" },
  { selector: "#otrg-programme option", index: 1, text: "Beginner Foundation — Ab €500" },
  { selector: "#otrg-programme option", index: 2, text: "Advanced Installation — Ab €1.200" },
  { selector: "#otrg-programme option", index: 3, text: "Master Business & Brand — Ab €2.500" },
  { selector: "#otrg-experience option", index: 0, text: "Level auswählen" },
  { selector: "#otrg-experience option", index: 1, text: "Beginner — Keine Vorerfahrung" },
  { selector: "#otrg-experience option", index: 2, text: "Intermediate — Erste Salon-Erfahrung" },
  { selector: "#otrg-experience option", index: 3, text: "Professional — Aktiv in der Branche" },
  { selector: "#otrg-experience option", index: 4, text: "Saloninhaberin" },
  { selector: "#otrg-message", attr: "placeholder", text: "Erzähl uns kurz von dir und deinen Zielen..." },
  { selector: "#otrg-apply-overlay .otrg-form-submit", text: "Bewerbung absenden" },
  { selector: "#otrg-apply-overlay .otrg-form-note", html: 'Schon angemeldet? <a href="#" onclick="otrgCloseApply(); otrgOpenLogin(); return false;">Zum Portal einloggen.</a>' },

  { selector: "#otrg-login-overlay .otrg-modal-eyebrow", text: "Student Portal" },
  { selector: "#otrg-login-overlay .otrg-modal-title", html: "Zugang zu deinem <em>Training Portal</em>" },
  { selector: "#otrg-login-overlay .otrg-modal-sub", text: "Gib deine Zugangsdaten ein. Diese erhältst du von OlivHairSupply, sobald deine Bewerbung bestätigt wurde." },
  { selector: ".otrg-form-label", index: 6, text: "E-Mail-Adresse" },
  { selector: ".otrg-form-label", index: 7, text: "Training Access Code" },
  { selector: "#otrg-login-code", attr: "placeholder", text: "Access Code eingeben" },
  { selector: "#otrg-login-error", text: "Die Angaben stimmen nicht. Bitte prüfe deine E-Mail-Adresse und deinen Access Code und versuche es erneut." },
  { selector: "#otrg-login-overlay .otrg-form-submit", text: "Training Portal öffnen" },
  { selector: "#otrg-login-overlay .otrg-form-note", html: 'Noch nicht angemeldet? <a href="#" onclick="otrgCloseLogin(); otrgOpenApply(); return false;">Für ein Schulungsprogramm bewerben.</a>' },
];

export function translateAttributes(element: Element, pairs: [string, string][]) {
  for (const attribute of TRANSLATABLE_ATTRIBUTES) {
    const current = element.getAttribute(attribute);
    if (!current) continue;
    let next = current;
    for (const [from, to] of pairs) {
      if (next.includes(from)) next = next.split(from).join(to);
    }
    if (next !== current) element.setAttribute(attribute, next);
  }
}

export function applyManualPageOverrides(root: ParentNode, lang: "de" | "en") {
  for (const override of HOME_PAGE_DE_OVERRIDES) {
    const matches = Array.from(root.querySelectorAll<HTMLElement>(override.selector));
    const elements = override.index === undefined ? matches : matches[override.index] ? [matches[override.index]] : [];

    for (const element of elements) {
      if (override.attr) {
        const originalKey = `ohsOriginal${override.attr.replace(/[^a-z]/gi, "")}`;
        if (!(originalKey in element.dataset)) {
          element.dataset[originalKey] = element.getAttribute(override.attr) || "";
        }
        if (lang === "de") element.setAttribute(override.attr, override.text || "");
        else element.setAttribute(override.attr, element.dataset[originalKey] || "");
        continue;
      }

      if (!("ohsOriginalHtml" in element.dataset)) {
        element.dataset.ohsOriginalHtml = element.innerHTML;
      }

      if (lang === "de") {
        if (override.html !== undefined) element.innerHTML = override.html;
        else element.textContent = override.text || "";
      } else {
        element.innerHTML = element.dataset.ohsOriginalHtml || "";
      }
    }
  }
}
