export const GERMAN_COPY_PAIRS: [string, string][] = [
  ["Luxury human hair extensions crafted for women who refuse compromise. Sourced from the world's finest suppliers, installed by Berlin's most trusted specialists.", "Luxuriöse Echthaar-Extensions für Frauen, die keine Kompromisse eingehen. Von den besten Lieferanten weltweit, installiert von Berlins renommiertesten Spezialisten."],
  ["Luxury extensions crafted for women who refuse compromise.", "Luxuriöse Extensions für Frauen, die keine Kompromisse eingehen."],
  ["Luxury Hair. Premium Quality. Every Strand Designed Just For You.", "Luxuriöses Haar. Premium-Qualität. Jede Strähne für dich perfektioniert."],
  ["Luxury Hair. Premium Quality. Designed for You.", "Luxuriöses Haar. Premium-Qualität. Für dich gemacht."],
  ["Stay connected with OlivHairSupply Club.", "Bleib immer auf dem Laufenden mit dem OlivHairSupply Club."],
  ["Stay connected with Olivhairsupply Club.", "Bleib immer auf dem Laufenden mit dem OlivHairSupply Club."],
  ["Worldwide Shipping — Free Over €200", "Weltweiter Versand – kostenlos ab 200 €"],
  ["Worldwide Shipping â€” Free Over â‚¬200", "Weltweiter Versand – kostenlos ab 200 €"],
  ["Free EU shipping on orders over €200", "Kostenloser EU-Versand ab 200 €"],
  ["Free EU Shipping Over €200", "Kostenloser EU-Versand ab 200 €"],
  ["FREE EU SHIPPING OVER €200", "KOSTENLOSER EU-VERSAND AB 200 €"],
  ["Free EU shipping on orders over â‚¬200", "Kostenloser EU-Versand ab 200 €"],
  ["Free EU Shipping Over â‚¬200", "Kostenloser EU-Versand ab 200 €"],
  ["FREE EU SHIPPING OVER â‚¬200", "KOSTENLOSER EU-VERSAND AB 200 €"],
  ["FREE EU SHIPPING", "KOSTENLOSER EU-VERSAND"],
  ["Free EU Shipping", "Kostenloser EU-Versand"],
  ["100% Human Hair", "100 % Echthaar"],
  ["100% HUMAN HAIR", "100 % ECHTHAAR"],
  ["Expert Colour Matching", "Professionelle Farbberatung"],
  ["EXPERT COLOUR MATCHING", "PROFESSIONELLE FARBBERATUNG"],
  ["Worldwide Delivery", "Weltweite Lieferung"],
  ["WORLDWIDE DELIVERY", "WELTWEITE LIEFERUNG"],
  ["Berlin In-Store Experience", "Berlin Salon-Erlebnis"],
  ["BERLIN IN-STORE EXPERIENCE", "BERLIN SALON-ERLEBNIS"],
  ["BiziLuxe Collection", "BiziLuxe Kollektion"],
  ["Shop BiziLuxe Hair", "BiziLuxe entdecken"],
  ["SHOP BIZILUXE HAIR", "BIZILUXE ENTDECKEN"],
  ["SHOP BIZILUXE", "BIZILUXE ENTDECKEN"],
  ["Book an Appointment", "Termin buchen"],
  ["Book Appointment", "Termin buchen"],
  ["BOOK APPOINTMENT", "TERMIN BUCHEN"],
  ["Premium Hair.", "Premium-Haar."],
  ["Confidence.", "Eleganz."],
  ["Effortless", "Mühelose"],
  ["Become an Affiliate →", "Affiliate-Partner werden →"],
  ["Become an Affiliate â†’", "Affiliate-Partner werden →"],
  ["Become an Affiliate", "Affiliate werden"],
  ["Affiliate Programme", "Affiliate-Programm"],
  ["Affiliate Program", "Affiliate-Programm"],
  ["Social Responsibility", "Soziale Verantwortung"],
  ["Track Order", "Bestellung verfolgen"],
  ["Stay Connected", "Verbunden bleiben"],
  ["STAY CONNECTED", "VERBUNDEN BLEIBEN"],
  ["Contact Us", "Kontakt"],
  ["Our Story", "Unsere Geschichte"],
  ["Sustainability", "Nachhaltigkeit"],
  ["Wholesale", "Großhandel"],
  ["Training", "Schulungen"],
  ["Appointment", "Termin buchen"],
  ["Careers", "Karriere"],
  ["Journal", "Magazin"],
  ["Returns", "Rücksendungen"],
  ["Shipping", "Versand"],
  ["Rentals", "Clip-in-Verleih"],
  ["Services", "Dienstleistungen"],
  ["Affiliate", "Affiliate"],
  ["About", "Über uns"],
  ["ABOUT", "ÜBER UNS"],
  ["Press", "Presse"],
  ["More", "Mehr"],
  ["MORE", "MEHR"],
  ["Help", "Hilfe"],
  ["HELP", "HILFE"],
  ["Home", "Startseite"],
  ["Shop", "Shop"],
  ["FAQ", "FAQ"],
  ["Language & Currency", "Sprache & Währung"],
  ["Language", "Sprache"],
  ["Currency", "Währung"],
  ["Search", "Suche"],
  ["Log in", "Anmelden"],
  ["Account", "Konto"],
  ["Cart", "Warenkorb"],
  ["Cart (0)", "Warenkorb (0)"],
  ["Open menu", "Menü öffnen"],
  ["Close menu", "Menü schließen"],
  ["First name", "Vorname"],
  ["Email address", "E-Mail-Adresse"],
  ["Subscribe", "Abonnieren"],
  ["Subscribe →", "Abonnieren →"],
  ["Subscribe &rarr;", "Abonnieren &rarr;"],
  ["No spam. Unsubscribe at any time.", "Kein Spam. Du kannst dich jederzeit abmelden."],
  ["Privacy Policy", "Datenschutzerklärung"],
  ["Terms and Conditions", "Allgemeine Geschäftsbedingungen"],
  ["All rights reserved.", "Alle Rechte vorbehalten."],
  ["Partner With OlivHairSupply", "Partner von OlivHairSupply werden"],
  ["Partner With ", "Partner von "],
  ["Partner With", "Partner von"],
  ["Become a wholesaler", "Werde Großhandelspartner"],
  ["Become a Wholesaler", "Werde Großhandelspartner"],
  ["Log Into Wholesale Shop", "Zum Großhandelsshop anmelden"],
  ["Log into Wholesale Shop", "Zum Großhandelsshop anmelden"],
  ["BiziLuxe Clip-In Collection", "BiziLuxe Clip-in-Kollektion"],
  ["Book Rental Consultation", "Beratung zur Anmietung buchen"],
  ["Speak to Our Team", "Unser Team kontaktieren"],
  ["Book Your Consultation", "Beratung buchen"],
  ["Luxury Hair ", "Luxuriöse Extensions zum "],
  ["Luxury Hair", "Luxuriöse Extensions"],
  ["Rentals.", "Mieten."],
  ["Our Services", "Unsere Dienstleistungen"],
  ["Tailored to You.", "für dein perfektes Haar."],
  ["Services ", "Individuelle Lösungen "],
  ["Book Training Consultation", "Beratungsgespräch buchen"],
  ["Become professionally ", "Werde professionell "],
  ["Become professionally", "Werde professionell"],
  ["Certified.", "zertifiziert."],
  ["Enroll Now", "Jetzt anmelden"],
  ["Berlin, Est. 2016", "Berlin, gegründet 2016"],
  ["Born from", "Aus Leidenschaft"],
  ["a passion", "entstanden"],
  ["The BiziLuxe Edit", "Die BiziLuxe Kollektion"],
  ["The BiziLuxe", "Die BiziLuxe"],
  ["Edit", "Kollektion"],
  ["100 %Cuticle-Aligned Human Hair", "100 % Echthaar mit intakter Schuppenschicht"],
  ["100% Cuticle-Aligned Human Hair", "100 % Echthaar mit intakter Schuppenschicht"],
  ["Cuticle-Aligned Human Hair", "Echthaar mit intakter Schuppenschicht"],
  ["6Collections", "6 Kollektionen"],
  ["6 Collections", "6 Kollektionen"],
  ["Collections", "Kollektionen"],
  ["Collection", "Kollektion"],
  ["EUWorldwide Shipping", "Weltweiter Versand"],
  ["EU Worldwide Shipping", "Weltweiter Versand"],
  ["Free ShippingOn orders over €200", "Kostenloser Versand ab 200 €"],
  ["Free Shipping On orders over €200", "Kostenloser Versand ab 200 €"],
  ["Free ShippingOn orders over â‚¬200", "Kostenloser Versand ab 200 €"],
  ["Free Shipping On orders over â‚¬200", "Kostenloser Versand ab 200 €"],
  ["On orders over €200", "Ab Bestellungen über 200 €"],
  ["On orders over â‚¬200", "Ab Bestellungen über 200 €"],
  ["14 Day ReturnsUnused sealed products", "14 Tage Rückgaberecht für unbenutzte und versiegelte Produkte"],
  ["14 Day Returns", "14 Tage Rückgaberecht"],
  ["Unused sealed products", "Für unbenutzte und versiegelte Produkte"],
  ["Expert GuidanceBook a free consultation", "Persönliche Beratung – kostenlose Beratung buchen"],
  ["Expert Guidance", "Persönliche Beratung"],
  ["Book a free consultation", "Kostenlose Beratung buchen"],
  ["EthicallySourcedQuality guaranteed", "Ethisch bezogen – garantierte Qualität"],
  ["Ethically SourcedQuality guaranteed", "Ethisch bezogen – garantierte Qualität"],
  ["Ethically Sourced", "Ethisch bezogen"],
  ["Quality guaranteed", "Garantierte Qualität"],
];

const TRANSLATABLE_ATTRIBUTES = ["aria-label", "title", "placeholder", "alt"] as const;

type ManualPageOverride = {
  selector: string;
  text?: string;
  html?: string;
  attr?: (typeof TRANSLATABLE_ATTRIBUTES)[number];
  index?: number;
};

const HOME_PAGE_DE_OVERRIDES: ManualPageOverride[] = [
  { selector: ".ohp-collections-header .ohp-eyebrow", text: "BiziLuxe Kollektion" },
  { selector: ".ohp-collections-header .ohp-col-title", html: "Nach Kategorie <em>entdecken</em>" },
  { selector: '.ohp-col-card[href="/collections/bizihair-extensions"] .ohp-col-tag', text: "BiziHair Haarverlängerungen" },
  { selector: '.ohp-col-card[href="/shop"] .ohp-col-tag', text: "BiziLuxe Hair" },
  { selector: '.ohp-col-card[href="/collections/biziluxe-tools"] .ohp-col-tag', text: "BiziLuxe Tools" },
  { selector: '.ohp-col-card[href="/collections/biziluxe-accessories"] .ohp-col-tag', text: "BiziLuxe Accessoires" },
  { selector: ".ohp-col-cta", text: "Entdecken" },

  { selector: ".ohp-featured-header .ohp-eyebrow", text: "Neuheiten" },
  { selector: ".ohp-featured-header .ohp-title", text: "Bestseller" },
  { selector: ".ohp-product-name", text: "BiziLuxe Produkt" },
  { selector: ".ohp-product-price", text: "Ab €0.00" },
  { selector: ".ohp-product-btn", text: "Jetzt kaufen" },
  { selector: ".ohp-featured-footer .ohp-btn-outline-dark", text: "Alle Produkte ansehen" },

  { selector: ".ohp-brand .ohp-eyebrow", text: "Unser Anspruch" },
  { selector: ".ohp-brand-quote", text: "Haare, die für sich selbst sprechen." },
  { selector: ".ohp-brand .ohp-body", index: 0, text: "BiziLuxe Haar ist für Frauen gemacht, die wissen: Qualität ist kein Luxus — sie ist Standard. Jedes Haar wird ausgewählt, jede Struktur wird beachtet, und jedes Produkt ist entwickelt, um sich zu bewegen, sich anzufühlen und genau wie echtes Premium-Haar zu funktionieren." },
  { selector: ".ohp-brand .ohp-body", index: 1, text: "Bei OlivHairSupply machen wir keine Kompromisse. Von unseren Berlin-Salons bis zur internationalen Lieferung — der Standard bleibt gleich." },
  { selector: ".ohp-brand .ohp-btn-outline-dark", text: "Unsere Geschichte" },

  { selector: ".ohp-block-warm .ohp-eyebrow", text: "OlivHairSupply Academy" },
  { selector: ".ohp-block-warm .ohp-title", text: "Werde zertifizierte Spezialistin." },
  { selector: ".ohp-block-warm .ohp-body", index: 0, text: "Lerne professionelle Einbautechniken, beherrsche das BiziLuxe System und baue deine Karriere im Premium-Bereich der Haarindustrie auf. Unsere Schulungsprogramme sind für Ehrgeiz gemacht." },
  { selector: ".ohp-block-warm .ohp-body", index: 1, text: "Drei Programme verfügbar — Foundation, Advanced und Master Business." },
  { selector: ".ohp-block-warm .ohp-btn-outline-dark", text: "Zur Schulung" },

  { selector: ".ohp-appointment .ohp-appt-eyebrow", text: "Dein Termin bei uns" },
  { selector: ".ohp-appointment .ohp-appt-title", text: "Dein Luxus-Erlebnis wartet." },
  { selector: ".ohp-appointment .ohp-appt-sub", text: "Besuche einen unserer Berlin-Salons für eine Premium-Haarverlängerung oder ein Premium-Styling. Fachleute, Luxusprodukte und ein Ergebnis, das spricht. Buche deinen Termin noch heute." },
  { selector: ".ohp-appointment .ohp-btn-ivory", text: "Termin vereinbaren" },
  { selector: ".ohp-appointment .ohp-btn-ivory-out", text: "Services ansehen" },

  { selector: ".ohp-block-ivory .ohp-eyebrow", text: "Clip-in-Verleih" },
  { selector: ".ohp-block-ivory .ohp-title", text: "Luxus-Haar für jeden Anlass." },
  { selector: ".ohp-block-ivory .ohp-body", index: 0, text: "Noch nicht kaufbereit? Unser Clip-in-Verleih gibt dir Zugang zu BiziLuxe Haarteilen für Events, Shoots oder besondere Anlässe — zu einem Bruchteil des Preises." },
  { selector: ".ohp-block-ivory .ohp-body", index: 1, text: "Verfügbar für Kunden in Berlin und ausgewählten Standorten. Kontaktiere uns, um die Verfügbarkeit für dein Event zu prüfen." },
  { selector: ".ohp-block-ivory .ohp-btn-outline-dark", text: "Clip-in-Verleih entdecken" },
  { selector: ".ohp-rental-image", attr: "alt", text: "OlivHairSupply Clip-in-Verleih" },

  { selector: ".ohp-testimonials-header .ohp-eyebrow", text: "Kunden-Geschichten" },
  { selector: ".ohp-testimonials-title", text: "Das sagen unsere Kunden" },
  { selector: ".ohp-testimonial-quote", index: 0, text: "Die Qualität von BiziLuxe Haar ist einfach unvergleichlich. Es verschmilzt perfekt und hält so viel länger als alles, das ich vorher getestet habe." },
  { selector: ".ohp-testimonial-quote", index: 1, text: "Mein Termin war vom Anfang bis zum Ende purer Luxus. Das Team bei OlivHairSupply versteht wirklich, was Premium-Service bedeutet." },
  { selector: ".ohp-testimonial-quote", index: 2, text: "Das Advanced Training hat meine Karriere komplett transformiert. Jetzt bediene ich eine Premium-Kundschaft und kann meine Arbeit fair bezahlen." },
  { selector: ".ohp-testimonial-loc", index: 0, text: "Berlin, Deutschland" },

  { selector: ".ohp-instagram-header .ohp-eyebrow", text: "Folge unserer Story" },
  { selector: ".ohp-instagram-footer .ohp-btn-outline-dark", text: "Auf Instagram folgen" },

  { selector: ".ohs-nl-section-eyebrow", text: "Das OlivHairSupply Edit" },
  { selector: ".ohs-nl-section-title", text: "Tritt dem OlivHairSupply Edit bei" },
  { selector: ".ohs-nl-section-sub", text: "Exklusive Drops, professionelle Haar-Tipps und Luxus-Updates direkt in dein Postfach." },
  { selector: '.ohs-nl-section-input[name="contact[first_name]"]', attr: "placeholder", text: "Vorname" },
  { selector: '.ohs-nl-section-input[name="contact[email]"]', attr: "placeholder", text: "E-Mail-Adresse" },
  { selector: ".ohs-nl-section-btn", text: "Anmelden →" },
  { selector: ".ohs-nl-section-note", text: "Kein Spam. Abmeldung jederzeit möglich." },

  { selector: ".ohp-trust .ohp-trust-text", index: 0, text: "100% Echthaar" },
  { selector: ".ohp-trust .ohp-trust-text", index: 1, text: "Versandkostenfrei EU ab €200" },
  { selector: ".ohp-trust .ohp-trust-text", index: 2, text: "Professionelle Farbberatung" },
  { selector: ".ohp-trust .ohp-trust-text", index: 3, text: "Weltweiter Versand" },
  { selector: ".ohs-trust .ohs-trust-text", index: 0, text: "100% Echthaar" },
  { selector: ".ohs-trust .ohs-trust-text", index: 1, text: "Versandkostenfrei EU ab €200" },
  { selector: ".ohs-trust .ohs-trust-text", index: 2, text: "Professionelle Farbberatung" },
  { selector: ".ohs-trust .ohs-trust-text", index: 3, text: "Weltweiter Versand" },

  { selector: ".oab-hero-eyebrow", text: "Berlin, seit 2016" },
  { selector: ".oab-hero-title", html: "Aus Leidenschaft <em>entstanden</em>" },
  { selector: ".oab-btn-hero-gold", text: "Karriere" },
  { selector: ".oab-btn-hero-dark", text: "Termin vereinbaren" },

  { selector: ".oab-story-text .oab-eyebrow", text: "Unsere Geschichte" },
  { selector: ".oab-story-title", html: "Von einem Stuhl<br>zu einer <em>Bewegung.</em>" },
  { selector: ".oab-story-text .oab-body", index: 0, text: "OlivHairSupply ist aus echter Erfahrung entstanden, nicht aus Theorie." },
  { selector: ".oab-story-text .oab-body", index: 1, text: "Nach Jahren praktischer Arbeit als Spezialistinnen für Haarverlängerungen, im Verkauf und in der Anwendung für unterschiedlichste Kundinnen, haben wir immer wieder dasselbe Problem gesehen: schwankende Haarqualität, unzuverlässige Tools und Produkte, die professionellen Ansprüchen einfach nicht gerecht wurden." },
  { selector: ".oab-story-text .oab-body", index: 2, text: "Statt das als Standard zu akzeptieren, haben wir uns entschieden, ihn neu zu definieren." },
  { selector: ".oab-story-text .oab-body", index: 3, text: "Durch kontinuierliches Kundenfeedback und tägliche Praxiserfahrung haben wir unser Verständnis dafür geschärft, was hochwertiges Haar wirklich ausmacht — von Struktur und Langlebigkeit bis zu Tragekomfort und Performance. Daraus entstanden Produkte, die den Erwartungen von Profis und Kundinnen gleichermaßen entsprechen." },
  { selector: ".oab-story-text .oab-body", index: 4, text: "Aber unsere Reise endete nicht beim Haar." },
  { selector: ".oab-story-text .oab-body", index: 5, text: "Als Spezialistinnen wissen wir aus eigener Erfahrung, wie schwer es ist, Tools und Geräte zu finden, die langlebig, effizient und wirklich für den Salonalltag gemacht sind. Viele Produkte am Markt halten langfristig nicht, was sie versprechen." },
  { selector: ".oab-story-text .oab-body", index: 6, text: "Deshalb haben wir BiziLuxe eingeführt: eine Premium-Linie professioneller Tools, Accessoires und Haarlösungen, sorgfältig recherchiert und ausgewählt für die Anforderungen moderner Hair Artists. Jedes Produkt wird mit Fokus auf Haltbarkeit, Präzision und einfache Anwendung ausgewählt." },
  { selector: ".oab-story-text .oab-body", index: 7, text: "Heute ist OlivHairSupply eine zentrale Adresse für hochwertiges Haar, professionelle Tools und ausgewählte Accessoires — aufgebaut auf Fachwissen, geformt durch echte Erfahrung und getragen von dem Anspruch, bessere Lösungen für Profis und Kundinnen zu schaffen." },
  { selector: ".oab-story-text .oab-body", index: 8, html: "Wir verkaufen nicht einfach Produkte.<br>Wir bieten Lösungen, denen wir vertrauen, die wir selbst nutzen und hinter denen wir stehen." },
  { selector: ".oab-story-text .oab-btn-dark", text: "Besuche uns" },

  { selector: ".oab-values > .oab-eyebrow", text: "Wofür wir stehen" },
  { selector: ".oab-values-title", html: "Unsere vier <em>Säulen.</em>" },
  { selector: ".oab-val-title", index: 0, text: "Qualität ohne Kompromisse" },
  { selector: ".oab-val-text", index: 0, text: "Jede Strähne ist 100% Remy-Echthaar, ethisch bezogen von vertrauenswürdigen Partnern. Wir prüfen jede Charge, bevor sie eine Kundin erreicht." },
  { selector: ".oab-val-title", index: 1, text: "Expertise, der du vertrauen kannst" },
  { selector: ".oab-val-text", index: 1, text: "Unsere Stylistinnen sind zertifiziert, intern geschult und leidenschaftlich in ihrem Handwerk. Präzision ist nicht nur unser Standard — sie ist unsere Identität." },
  { selector: ".oab-val-title", index: 2, text: "Wirklich maßgeschneidert" },
  { selector: ".oab-val-text", index: 2, text: "Kein Haar ist wie das andere. Jede Beratung, jede Einarbeitung und jede Pflegeempfehlung wird auf dich und deinen Lebensstil abgestimmt." },
  { selector: ".oab-val-title", index: 3, text: "Community und Selbstbewusstsein" },
  { selector: ".oab-val-text", index: 3, text: "OlivHairSupply ist mehr als ein Salon. Wir sind eine Community von Frauen, die daran glauben: Sich schön zu fühlen ist kein Luxus — es ist ein Recht." },

  { selector: ".oab-tl-header .oab-eyebrow", text: "Unser Weg" },
  { selector: ".oab-tl-title", html: "Wachsen mit <em>Anspruch.</em>" },
  { selector: ".oab-tl-name", index: 0, text: "Die Gründung" },
  { selector: ".oab-tl-body", index: 0, text: "OlivHairSupply startet als Online-Shop mit klarem Fokus: hochwertige Haarverlängerungen für Kundinnen in ganz Deutschland zu sourcen und verfügbar zu machen." },
  { selector: ".oab-tl-name", index: 1, text: "Online-Shop Launch" },
  { selector: ".oab-tl-body", index: 1, text: "Wir launchen olivhairsupply.de und bringen unsere kuratierten BiziHair- und Olivhairlux-Kollektionen zu Kundinnen in ganz Europa." },
  { selector: ".oab-tl-name", index: 2, text: "Eröffnung in Schöneberg" },
  { selector: ".oab-tl-body", index: 2, text: "Der erste Salon- und Retail-Standort in Berlin-Schöneberg entsteht auf 60 qm — mit Produktverkauf und zwei Plätzen für Haarverlängerungen." },
  { selector: ".oab-tl-name", index: 3, text: "Expansion und Wachstum" },
  { selector: ".oab-tl-body", index: 3, text: "Aufgrund steigender Nachfrage erweitert sich der Standort auf 100 qm mit vier Plätzen für Haarverlängerungen." },
  { selector: ".oab-tl-name", index: 4, text: "Planung und Strategie" },
  { selector: ".oab-tl-body", index: 4, text: "Ein Jahr im Zeichen langfristiger Expansion, Struktur und Vorbereitung." },
  { selector: ".oab-tl-name", index: 5, text: "Expansion am Kurfürstendamm" },
  { selector: ".oab-tl-body", index: 5, text: "Der zweite Standort wird in einer der renommiertesten Retail-Lagen Berlins gesichert." },
  { selector: ".oab-badge.coming", text: "Demnächst" },
  { selector: ".oab-tl-name", index: 6, text: "Flagship Launch (290 qm)" },
  { selector: ".oab-tl-body", index: 6, text: "Full-Service Flagship Store mit Premium-Haar, professionellen Tools, Geräten und B2B-Zugang." },
  { selector: ".oab-btn-sm", text: "Als Erste erfahren" },
  { selector: ".oab-btn-sm-out", text: "Kontakt aufnehmen" },

  { selector: ".oab-exp-title", html: "Wir wachsen in Berlin.<br><em>Der zweite Standort kommt.</em>" },
  { selector: ".oab-exp-body", text: "Unser zweiter Standort ist auf dem Weg. Mehr Raum. Mehr Stylistinnen. Mehr von dem OlivHairSupply Erlebnis, das du liebst. Trag dich in unseren Newsletter ein und erfahre die Neuigkeiten als Erste." },
  { selector: ".oab-btn-ivory", text: "Zur Warteliste" },
  { selector: ".oab-btn-ivory-out", text: "Kontakt" },

  { selector: ".oab-team-header .oab-eyebrow", text: "Die Menschen hinter OlivHairSupply" },
  { selector: ".oab-team-title", html: "Lerne unsere <em>Hair Specialists</em> kennen" },
  { selector: ".oab-team-intro", text: "Bei OlivHairSupply folgt jeder Service einem klar definierten Standard aus Qualität, Präzision und Beständigkeit. Unser Spezialistinnen-Team ist geschult, damit jede Kundin ein nahtloses, individuell abgestimmtes Ergebnis erhält — unabhängig von der Stylistin." },
  { selector: ".oab-team-role", index: 0, text: "Gründerin und Creative Director" },
  { selector: ".oab-team-specialty", index: 0, text: "Advanced Colour Blending, alle Extension-Methoden und Stylistinnen-Training" },
  { selector: ".oab-team-bio", index: 0, text: "Setzt den OlivHairSupply Standard und verantwortet Qualität, Ausbildung und Produktentwicklung an allen Standorten. Termine nur begrenzt verfügbar." },
  { selector: ".oab-team-role", index: 1, text: "Extension- und Perückenspezialistin" },
  { selector: ".oab-team-specialty", index: 1, text: "Weaving, Tape-ins, Full Weaves, Perückeninstallationen und Braiding" },
  { selector: ".oab-team-bio", index: 1, text: "Mit umfassender Praxiserfahrung liefert sie vielseitige, gepflegte und langanhaltende Ergebnisse." },
  { selector: ".oab-team-role", index: 2, text: "Client Experience und Senior Extension Specialist" },
  { selector: ".oab-team-specialty", index: 2, text: "Bondings, Tape-ins und präzise Farbabstimmung" },
  { selector: ".oab-team-bio", index: 2, text: "Mit über 15 Jahren Erfahrung bietet sie fachkundige Beratung und perfektes Matching." },
  { selector: ".oab-team-role", index: 3, text: "Senior Extension Specialist" },
  { selector: ".oab-team-specialty", index: 3, text: "Weaving, Brazilian Knots, Tape-ins, Keratin-Bondings und Braiding" },
  { selector: ".oab-team-bio", index: 3, text: "Nach OlivHairSupply Standards geschult und spezialisiert auf nahtlose, natürliche Ergebnisse." },
  { selector: ".oab-team-role", index: 4, text: "Senior Braiding und Extension Specialist" },
  { selector: ".oab-team-specialty", index: 4, text: "Braids, Cornrows, Weaving und Brazilian Knots" },
  { selector: ".oab-team-bio", index: 4, text: "Mit über 15 Jahren Erfahrung, bekannt für Präzision, saubere Finishes und hohen Kundenkomfort." },

  { selector: ".otr-hero-img", attr: "alt", text: "OlivHairSupply Academy" },
  { selector: ".otr-eyebrow", text: "OlivHairSupply Academy" },
  { selector: ".otr-hero-title", html: "Werde professionell <em>zertifiziert.</em>" },
  { selector: ".otrn-btn-gold", text: "Jetzt anmelden" },
  { selector: ".otrn-btn-dark", text: "Beratung zur Schulung buchen" },

  { selector: ".otrg-img-label", index: 0, text: "Präzises Arbeiten" },
  { selector: ".otrg-img-title", index: 0, html: "Expertinnen-Hände.<br><em>Jedes Detail.</em>" },
  { selector: ".otrg-img-label", index: 1, text: "Styling & Finish" },
  { selector: ".otrg-img-title", index: 1, html: "Makellos.<br><em>Jedes Mal.</em>" },

  { selector: ".otr-value .otr-section-eyebrow", text: "Warum diese Schulung anders ist" },
  { selector: ".otr-value .otr-section-title", html: "Mehr als Training.<br><em>Ein Business-Upgrade.</em>" },
  { selector: ".otr-value-lead", text: "Hier geht es nicht nur darum, Haare zu lernen." },
  { selector: ".otr-value-body", text: "In der OlivHairSupply Academy lernst du, Premium-Ergebnisse für Kundinnen zu liefern, mit luxuriösem BiziLuxe Haar zu arbeiten und eine Marke aufzubauen, die den Preis verdient, den deine Arbeit wert ist." },
  { selector: ".otr-value-point", index: 0, text: "Premium-Ergebnisse liefern, die Empfehlungen auslösen" },
  { selector: ".otr-value-point", index: 1, text: "Sicher mit luxuriösen BiziLuxe Haarsystemen arbeiten" },
  { selector: ".otr-value-point", index: 2, text: "Deine Services klar und selbstbewusst kalkulieren" },
  { selector: ".otr-value-point", index: 3, text: "Eine nachhaltige und profitable Beauty-Marke aufbauen" },
  { selector: ".otr-value-img-ph span", text: "Schulungsbild" },

  { selector: ".otr-programmes-header .otr-section-eyebrow", text: "Wähle dein Programm" },
  { selector: ".otr-programmes-header .otr-section-title", html: "Investiere in deine <em>Zukunft</em>" },
  { selector: ".otr-programmes-header .otr-section-sub", text: "Drei strukturierte Programme, die dich vom Fundament bis zur Meisterschaft führen." },
  { selector: ".otr-prog-badge", index: 1, text: "Am beliebtesten" },
  { selector: ".otr-prog-name", index: 0, text: "Beginner Foundation" },
  { selector: ".otr-prog-duration", index: 0, text: "1 Tag Intensiv" },
  { selector: ".otr-prog-price", index: 0, text: "Ab €500" },
  { selector: ".otr-prog-price", index: 1, text: "Ab €1200" },
  { selector: ".otr-prog-price", index: 2, text: "Ab €2500" },
  { selector: ".otr-prog-price-label", text: "Alle Materialien inklusive" },
  { selector: ".otr-prog-desc", index: 0, text: "Starte deine Reise in die Premium-Haarverlängerung mit starken Grundlagen, fachlicher Begleitung und dem Selbstvertrauen, ab Tag eins Ergebnisse zu liefern." },
  { selector: ".otr-prog-desc", index: 1, text: "Meistere nahtlose Einarbeitungen über mehrere Systeme hinweg und hebe deinen professionellen Standard auf das Niveau des Luxusmarktes." },
  { selector: ".otr-prog-desc", index: 2, text: "Für Profis, die bereit sind, eine Luxusmarke aufzubauen und ein einkommensstarkes Business mit Premium-Kundinnen zu entwickeln." },
  { selector: ".otr-prog-includes li", index: 0, text: "Einführung in Haarverlängerungen" },
  { selector: ".otr-prog-includes li", index: 1, text: "Grundlegende Extension-Methoden" },
  { selector: ".otr-prog-includes li", index: 2, text: "Beratungskompetenz für Kundinnen" },
  { selector: ".otr-prog-includes li", index: 3, text: "Pflegeempfehlung und Systeme" },
  { selector: ".otr-prog-includes li", index: 4, text: "Tape-ins meistern" },
  { selector: ".otr-prog-includes li", index: 5, text: "Hand-tied Wefts" },
  { selector: ".otr-prog-includes li", index: 6, text: "Blending und Styling" },
  { selector: ".otr-prog-includes li", index: 7, text: "Fortgeschrittene Extension-Methoden" },
  { selector: ".otr-prog-includes li", index: 8, text: "Premium-Kundenerlebnis" },
  { selector: ".otr-prog-includes li", index: 9, text: "Preisstrategie" },
  { selector: ".otr-prog-includes li", index: 10, text: "Branding und Positionierung" },
  { selector: ".otr-prog-includes li", index: 11, text: "Kundengewinnung und Kundenbindung" },
  { selector: ".otr-prog-cta", text: "Jetzt anmelden" },

  { selector: ".otr-master-header .otr-section-eyebrow", text: "Curriculum" },
  { selector: ".otr-master-header .otr-section-title", html: "Was du <em>meisterst</em>" },
  { selector: ".otr-master-header .otr-section-sub", text: "Jedes Modul ist darauf ausgelegt, dich zu einer vollständigen, hochwertigen Fachperson zu entwickeln." },
  { selector: ".otr-master-title", index: 0, text: "Haar-Sourcing und Qualitätskontrolle" },
  { selector: ".otr-master-text", index: 0, text: "Verstehe, was Premium-Haar ausmacht und wie du Qualität in jeder Phase bewertest." },
  { selector: ".otr-master-title", index: 1, text: "Präzise Einarbeitung" },
  { selector: ".otr-master-text", index: 1, text: "Meistere die technischen Fähigkeiten für makellose, langanhaltende Einarbeitungen." },
  { selector: ".otr-master-title", index: 2, text: "Farbabstimmung und Blending" },
  { selector: ".otr-master-text", index: 2, text: "Schule dein Auge, um natürliche Farbtöne nahtlos abzustimmen und zu verblenden." },
  { selector: ".otr-master-title", index: 3, text: "Styling und Finish" },
  { selector: ".otr-master-text", index: 3, text: "Liefere Styling-Ergebnisse auf Editorial-Niveau, die das gesamte Kundenerlebnis aufwerten." },
  { selector: ".otr-master-title", index: 4, text: "Kundenberatung" },
  { selector: ".otr-master-text", index: 4, text: "Führe sichere, professionelle Beratungen, die Vertrauen schaffen und Buchungen sichern." },
  { selector: ".otr-master-title", index: 5, text: "Pflegeempfehlung" },
  { selector: ".otr-master-text", index: 5, text: "Gib jeder Kundin einen vollständigen Pflegeplan, der deine Arbeit schützt und Loyalität aufbaut." },
  { selector: ".otr-master-title", index: 6, text: "Preisgestaltung und Profitabilität" },
  { selector: ".otr-master-text", index: 6, text: "Lerne, deine Services so zu kalkulieren, dass sie deinen Wert widerspiegeln und nachhaltiges Einkommen schaffen." },
  { selector: ".otr-master-title", index: 7, text: "Business- und Markenaufbau" },
  { selector: ".otr-master-text", index: 7, text: "Positioniere dich als Luxus-Spezialistin und ziehe Kundinnen an, die deine Arbeit wertschätzen." },

  { selector: ".otr-who .otr-section-eyebrow", text: "Ist das für dich?" },
  { selector: ".otr-who .otr-section-title", html: "Gemacht für <em>Ehrgeiz.</em>" },
  { selector: ".otr-who .otr-section-sub", text: "Unsere Programme sind für alle, die ernsthaft eine Karriere im Premium-Bereich der Haarindustrie aufbauen wollen." },

  { selector: ".otr-cert .otr-section-eyebrow", text: "Offizielle Anerkennung" },
  { selector: ".otr-cert-title", html: "Erhalte deine <em>Zertifizierung</em>" },
  { selector: ".otr-cert-text", index: 0, text: "Nach Abschluss deines Programms erhältst du eine offizielle OlivHairSupply Zertifizierung, die deine Expertise in luxuriösen Haarsystemen und Premium-Service bestätigt." },
  { selector: ".otr-cert-text", index: 1, text: "Dein Zertifikat ist ein Qualitätszeichen. Es zeigt Kundinnen und Arbeitgebern, dass du nach dem OlivHairSupply Standard ausgebildet wurdest." },
  { selector: ".otr-cert .otr-btn-gold", text: "Jetzt anmelden" },
  { selector: ".otr-cert-badge-sub", text: "Zertifizierte Spezialistin" },
  { selector: ".otr-cert-badge-text", text: "Verliehen nach erfolgreichem Abschluss des OlivHairSupply Academy Programms." },

  { selector: ".otr-exp-header .otr-section-eyebrow", text: "Das Erlebnis" },
  { selector: ".otr-exp-header .otr-section-title", html: "Training, das sich <em>anders anfühlt.</em>" },
  { selector: ".otr-exp-title", index: 0, text: "Kleine Gruppen" },
  { selector: ".otr-exp-text", index: 0, text: "Intime Gruppen sorgen dafür, dass jede Teilnehmerin direkte Aufmerksamkeit, persönliches Feedback und echte Entwicklung erhält." },
  { selector: ".otr-exp-title", index: 1, text: "Praxisnahes Training" },
  { selector: ".otr-exp-text", index: 1, text: "Jede Session ist praktisch. Du arbeitest mit echtem Haar, echten Kundinnen und realen Szenarien vom ersten Tag an." },
  { selector: ".otr-exp-title", index: 2, text: "Direkte Expertenbegleitung" },
  { selector: ".otr-exp-text", index: 2, text: "Lerne direkt von OlivHairSupply Spezialistinnen mit jahrelanger Erfahrung in luxuriöser Einarbeitung und Business." },
  { selector: ".otr-exp-title", index: 3, text: "Reale Kundenszenarien" },
  { selector: ".otr-exp-text", index: 3, text: "Trainiere unter Bedingungen, die das echte Premium-Kundenerlebnis widerspiegeln — von der Beratung bis zum finalen Ergebnis." },

  { selector: ".otr-cta-eyebrow", text: "Dein nächster Schritt" },
  { selector: ".otr-cta-title", html: "Starte deine<br><em>Luxus-Karriere</em>" },
  { selector: ".otr-cta-sub", text: "Die Plätze sind begrenzt. Sichere dir heute deinen Platz und beginne deinen Weg zur zertifizierten Luxus-Haar-Spezialistin." },
  { selector: ".otr-btn-cta-primary", text: "Jetzt bewerben" },
  { selector: ".otr-btn-cta-outline", text: "Beratung zur Schulung buchen" },

  { selector: "#otrg-apply-close", attr: "aria-label", text: "Schließen" },
  { selector: "#otrg-login-close", attr: "aria-label", text: "Schließen" },
  { selector: "#otrg-apply-overlay .otrg-modal-eyebrow", text: "Schulungsbewerbung" },
  { selector: "#otrg-apply-overlay .otrg-modal-title", html: "Für die <em>Zertifizierung</em> bewerben" },
  { selector: "#otrg-apply-overlay .otrg-modal-sub", text: "Fülle das Formular aus. Unser Team prüft jede Bewerbung persönlich und meldet sich innerhalb von 3 bis 5 Werktagen bei dir." },
  { selector: ".otrg-form-label", index: 0, text: "Vollständiger Name" },
  { selector: ".otrg-form-label", index: 1, text: "E-Mail-Adresse" },
  { selector: ".otrg-form-label", index: 2, text: "Telefonnummer" },
  { selector: ".otrg-form-label", index: 3, text: "Gewünschtes Programm" },
  { selector: ".otrg-form-label", index: 4, text: "Aktuelles Erfahrungslevel" },
  { selector: ".otrg-form-label", index: 5, text: "Warum möchtest du bei uns lernen?" },
  { selector: "#otrg-name", attr: "placeholder", text: "Dein vollständiger Name" },
  { selector: "#otrg-programme option", index: 0, text: "Programm auswählen" },
  { selector: "#otrg-programme option", index: 1, text: "Beginner Foundation — Ab €500" },
  { selector: "#otrg-programme option", index: 2, text: "Advanced Installation — Ab €1.200" },
  { selector: "#otrg-programme option", index: 3, text: "Master Business & Brand — Ab €2.500" },
  { selector: "#otrg-experience option", index: 0, text: "Level auswählen" },
  { selector: "#otrg-experience option", index: 1, text: "Beginner — Keine Vorerfahrung" },
  { selector: "#otrg-experience option", index: 2, text: "Intermediate — Erste Salon-Erfahrung" },
  { selector: "#otrg-experience option", index: 3, text: "Professional — Aktiv in der Branche" },
  { selector: "#otrg-experience option", index: 4, text: "Saloninhaberin" },
  { selector: "#otrg-message", attr: "placeholder", text: "Erzähl uns kurz von dir und deinen Zielen..." },
  { selector: "#otrg-apply-overlay .otrg-form-submit", text: "Bewerbung absenden" },
  { selector: "#otrg-apply-overlay .otrg-form-note", html: 'Schon angemeldet? <a href="#" onclick="otrgCloseApply(); otrgOpenLogin(); return false;">Zum Portal einloggen.</a>' },

  { selector: "#otrg-login-overlay .otrg-modal-eyebrow", text: "Student Portal" },
  { selector: "#otrg-login-overlay .otrg-modal-title", html: "Zugang zu deinem <em>Training Portal</em>" },
  { selector: "#otrg-login-overlay .otrg-modal-sub", text: "Gib deine Zugangsdaten ein. Diese erhältst du von OlivHairSupply, sobald deine Bewerbung bestätigt wurde." },
  { selector: ".otrg-form-label", index: 6, text: "E-Mail-Adresse" },
  { selector: ".otrg-form-label", index: 7, text: "Training Access Code" },
  { selector: "#otrg-login-code", attr: "placeholder", text: "Access Code eingeben" },
  { selector: "#otrg-login-error", text: "Die Angaben stimmen nicht. Bitte prüfe deine E-Mail-Adresse und deinen Access Code und versuche es erneut." },
  { selector: "#otrg-login-overlay .otrg-form-submit", text: "Training Portal öffnen" },
  { selector: "#otrg-login-overlay .otrg-form-note", html: 'Noch nicht angemeldet? <a href="#" onclick="otrgCloseLogin(); otrgOpenApply(); return false;">Für ein Schulungsprogramm bewerben.</a>' },

  { selector: ".osv-hero-img", attr: "alt", text: "Luxus-Haarservices" },
  { selector: ".osv-hero .osv-eyebrow", text: "Unsere Services" },
  { selector: ".osv-hero-title", html: "Services <em>für dich gemacht.</em>" },
  { selector: ".osv-whl-btns .osv-btn-gold", text: "Termin vereinbaren" },
  { selector: ".osv-whl-btns .osv-btn-dark", text: "Clip-in-Verleih" },
  { selector: ".osv-intro-text", text: "OlivHairSupply verbindet Salon-Expertise mit Premium-Haar. Ob Einarbeitung, Pflege oder komplette Veränderung deines Looks — unsere Spezialistinnen liefern Präzision, Qualität und Ergebnisse, die halten." },
  { selector: ".osv-section-header .osv-eyebrow", text: "Was wir anbieten" },
  { selector: ".osv-section-header .osv-section-title", html: "Unsere <em>Services</em>" },
  { selector: ".osv-section-header .osv-section-sub", text: "Jeder Service folgt dem OlivHairSupply Standard — präzise, persönlich und premium." },
  { selector: ".osv-pillar-img-ph span", index: 0, text: "Haarverlängerung" },
  { selector: ".osv-pillar-img-ph span", index: 1, text: "Farbabstimmung" },
  { selector: ".osv-pillar-img-ph span", index: 2, text: "Home Service" },
  { selector: ".osv-pillar-img-ph span", index: 3, text: "Professionelle Schulung" },
  { selector: ".osv-pillar-title", index: 0, text: "Haarverlängerung" },
  { selector: ".osv-pillar-desc", index: 0, text: "Fachgerechte Einarbeitung mit BiziLuxe Premium-Haarverlängerungen. Nahtlose Übergänge, natürliche Bewegung und langanhaltende Ergebnisse." },
  { selector: ".osv-pillar-includes li", index: 0, text: "Clip-ins anpassen" },
  { selector: ".osv-pillar-includes li", index: 1, text: "Tape-ins" },
  { selector: ".osv-pillar-includes li", index: 2, text: "Hand-tied Wefts" },
  { selector: ".osv-pillar-includes li", index: 3, text: "Perücken-Einarbeitung" },
  { selector: ".osv-pillar-title", index: 1, text: "Farbe und Customisation" },
  { selector: ".osv-pillar-desc", index: 1, text: "Präzise Farbabstimmung und individuelle Anpassung, abgestimmt auf deinen Ton, deinen Stil und dein gewünschtes Finish." },
  { selector: ".osv-pillar-includes li", index: 4, text: "Farbabstimmung" },
  { selector: ".osv-pillar-includes li", index: 5, text: "Toning" },
  { selector: ".osv-pillar-includes li", index: 6, text: "Blending" },
  { selector: ".osv-pillar-includes li", index: 7, text: "Individuelles Styling" },
  { selector: ".osv-pillar-title", index: 2, text: "Luxury Home Service" },
  { selector: ".osv-pillar-desc", index: 2, text: "Salonqualität bei dir zu Hause. Für Kundinnen, die Privatsphäre, Komfort und ein Premium-Erlebnis schätzen." },
  { selector: ".osv-pillar-includes li", index: 8, text: "Komplette Einarbeitung zu Hause" },
  { selector: ".osv-pillar-includes li", index: 9, text: "Persönliche Beratung" },
  { selector: ".osv-pillar-includes li", index: 10, text: "Mobiler Service nach Absprache" },
  { selector: ".osv-pillar-title", index: 3, text: "Professionelle Schulung" },
  { selector: ".osv-pillar-desc", index: 3, text: "Lerne von Branchenprofis und meistere die Kunst der luxuriösen Haar-Einarbeitung mit BiziLuxe Produkten." },
  { selector: ".osv-pillar-includes li", index: 11, text: "Beginner-Kurse" },
  { selector: ".osv-pillar-includes li", index: 12, text: "Fortgeschrittene Extension-Methoden" },
  { selector: ".osv-pillar-includes li", index: 13, text: "Zertifizierungs-Training" },
  { selector: ".osv-pillar-cta", index: 0, text: "Jetzt buchen" },
  { selector: ".osv-pillar-cta", index: 1, text: "Beratung buchen" },
  { selector: ".osv-pillar-cta", index: 2, text: "Home Service anfragen" },
  { selector: ".osv-pillar-cta", index: 3, text: "Schulung buchen" },
  { selector: ".osv-process-header .osv-eyebrow", text: "So funktioniert es" },
  { selector: ".osv-process-title", html: "Dein <em>Weg</em>" },
  { selector: ".osv-process-sub", text: "Vom ersten Kontakt bis zum finalen Ergebnis — ein nahtloses Premium-Erlebnis." },
  { selector: ".osv-step-title", index: 0, text: "Beratung buchen" },
  { selector: ".osv-step-desc", index: 0, text: "Starte mit einer persönlichen Beratung. Wir hören zu, analysieren und entwickeln den passenden Serviceplan für deine Haarziele." },
  { selector: ".osv-step-title", index: 1, text: "Haarauswahl" },
  { selector: ".osv-step-desc", index: 1, text: "Wähle aus unserer kuratierten BiziLuxe Range. Wir stimmen Länge, Struktur und Farbe präzise auf dein natürliches Haar ab." },
  { selector: ".osv-step-title", index: 2, text: "Einarbeitung und Service" },
  { selector: ".osv-step-desc", index: 2, text: "Deine Spezialistin arbeitet mit professioneller Technik für eine makellose Einarbeitung. Komfort, Präzision und Handwerk — jedes Mal." },
  { selector: ".osv-step-title", index: 3, text: "Pflegeempfehlung und Maintenance" },
  { selector: ".osv-step-desc", index: 3, text: "Wir führen dich durch eine persönliche Pflegeroutine, damit dein Haar so lange wie möglich in perfektem Zustand bleibt." },
  { selector: ".osv-pricing-eyebrow", text: "Investition in Qualität" },
  { selector: ".osv-pricing-title", html: "Premium-Service,<br><em>Premium-Qualität.</em>" },
  { selector: ".osv-pricing-text", index: 0, text: "Premium-Service braucht Premium-Qualität. Unsere Preise spiegeln die Expertise unserer Stylistinnen, die Qualität von BiziLuxe Haar und das individuell abgestimmte Erlebnis wider." },
  { selector: ".osv-pricing-text", index: 1, text: "Wir machen keine Kompromisse bei Materialien oder Technik. Was wir anbieten, ist eine Investition in Haar, das auf höchstem Niveau aussieht, sich so anfühlt und funktioniert." },
  { selector: ".osv-pricing-note", text: "Die Beratungsgebühr wird auf den Service angerechnet." },
  { selector: ".osv-pp-title", index: 0, text: "Transparente Preise" },
  { selector: ".osv-pp-text", index: 0, text: "Deine Spezialistin erstellt während der Beratung ein vollständiges Angebot. Keine versteckten Kosten, keine Überraschungen." },
  { selector: ".osv-pp-title", index: 1, text: "Flexible Zahlung" },
  { selector: ".osv-pp-text", index: 1, text: "Eine Anzahlung sichert deinen Termin. Der Restbetrag ist am Tag deines Services fällig." },
  { selector: ".osv-pp-title", index: 2, text: "Sicher und vertrauensvoll" },
  { selector: ".osv-pp-text", index: 2, text: "Alle Zahlungen werden sicher verarbeitet. Deine Zufriedenheit ist durch unseren Qualitätsanspruch abgesichert." },
  { selector: ".osv-cta-eyebrow", text: "Mach den nächsten Schritt" },
  { selector: ".osv-cta-title", html: "Bereit, dein Haar<br><em>zu veredeln?</em>" },
  { selector: ".osv-cta-sub", text: "Buche heute deine Beratung und starte deinen Weg zu makellosem Luxus-Haar mit OlivHairSupply." },
  { selector: ".osv-cta .osv-btn-gold", text: "Termin vereinbaren" },
  { selector: ".osv-cta .osv-btn-outline-dark", text: "Kontakt" },

  { selector: ".orn-hero-img", attr: "alt", text: "Luxus-Haarverleih" },
  { selector: ".orn-eyebrow", text: "BiziLuxe Clip-in-Kollektion" },
  { selector: ".orn-hero-title", html: "Luxus-Haar <em>zum Mieten.</em>" },
  { selector: ".orn-hero-sub", text: "Premium-Clip-ins für Hochzeiten, Shootings, Galas und unvergessliche Anlässe." },
  { selector: ".orn-hero-btns .orn-btn-gold", text: "Beratung zum Verleih buchen" },
  { selector: ".orn-hero-btns .orn-btn-outline-light", text: "Unser Team kontaktieren" },
  { selector: ".orn-stat-label", index: 0, text: "Anlässe" },
  { selector: ".orn-stat-label", index: 1, text: "Nur im Berliner Salon" },
  { selector: ".orn-stat-label", index: 2, text: "Farblich abgestimmt" },
  { selector: ".orn-stat-label", index: 3, text: "Nur mit Termin" },
  { selector: ".orn-intro .orn-section-eyebrow", text: "Das Verleih-Erlebnis" },
  { selector: ".orn-intro .orn-section-title", html: "Luxus-Haar für<br><em>besondere Momente.</em>" },
  { selector: ".orn-intro-lead", text: "Mehr als ein Accessoire. Ein komplettes Luxus-Erlebnis." },
  { selector: ".orn-intro-body", index: 0, text: "Du wünschst dir volleres, längeres, glamouröses Haar für deine Hochzeit, ein Fotoshooting, eine Gala, deinen Geburtstag oder ein besonderes Event? Unsere BiziLuxe Clip-in-Kollektion schenkt dir sofort Volumen, Länge und Eleganz für unvergessliche Styling-Momente." },
  { selector: ".orn-intro-body", index: 1, text: "Für ausgewählte Bridal- und VIP-Kundinnen bieten wir einen exklusiven Clip-in-Verleih im Salon mit Abholung und Rückgabe in Berlin. Jedes Set wird während deiner Beratung professionell farblich abgestimmt, damit dein Look nahtlos, luxuriös und individuell wirkt." },
  { selector: ".orn-intro-point", index: 0, text: "Nur mit Termin verfügbar" },
  { selector: ".orn-intro-point", index: 1, text: "Abholung und Rückgabe im Berliner Salon" },
  { selector: ".orn-intro-point", index: 2, text: "Verleihgebühr und erstattbare Kaution" },
  { selector: ".orn-intro-point", index: 3, text: "Je nach Verfügbarkeit" },
  { selector: ".orn-intro-img-ph span", text: "BiziLuxe Kollektion" },
  { selector: ".orn-occasions .orn-section-eyebrow", text: "Perfekt für" },
  { selector: ".orn-occasions .orn-section-title", html: "Deinen <em>besonderen Anlass</em>" },
  { selector: ".orn-occasions .orn-section-sub", text: "Von intimen Zeremonien bis zu großen Galas — unsere BiziLuxe Verleih-Kollektion veredelt jeden Moment." },
  { selector: ".orn-occasion-label", text: "Anlass" },
  { selector: ".orn-occasion-name", index: 0, text: "Hochzeiten" },
  { selector: ".orn-occasion-name", index: 1, text: "Fotoshootings" },
  { selector: ".orn-occasion-name", index: 2, text: "Galas" },
  { selector: ".orn-occasion-name", index: 3, text: "Geburtstage" },
  { selector: ".orn-occasion-name", index: 4, text: "Bridal Styling" },
  { selector: ".orn-occasion-name", index: 5, text: "VIP Events" },
  { selector: ".orn-how .orn-section-eyebrow", text: "Der Prozess" },
  { selector: ".orn-how .orn-section-title", html: "So <em>funktioniert es</em>" },
  { selector: ".orn-how .orn-section-sub", text: "Ein nahtlos geführtes Erlebnis von der Buchung bis zu deinem großen Tag." },
  { selector: ".orn-step-title", index: 0, text: "Termin buchen" },
  { selector: ".orn-step-text", index: 0, text: "Frage deine Verleih-Beratung online an. Unser Team bestätigt deinen Termin und bereitet deinen Besuch vor." },
  { selector: ".orn-step-title", index: 1, text: "Farbabstimmung im Salon" },
  { selector: ".orn-step-text", index: 1, text: "Besuche unseren Berliner Salon für eine professionelle Farbberatung. Wir stimmen dein BiziLuxe Set präzise auf dein natürliches Haar ab." },
  { selector: ".orn-step-title", index: 2, text: "Set auswählen" },
  { selector: ".orn-step-text", index: 2, text: "Wähle aus unserer kuratierten BiziLuxe Clip-in-Kollektion. Deine Stylistin führt dich zu den besten Optionen für Anlass und Stil." },
  { selector: ".orn-step-title", index: 3, text: "Verleihgebühr und Kaution zahlen" },
  { selector: ".orn-step-text", index: 3, text: "Eine Verleihgebühr und eine vollständig erstattbare Kaution sind erforderlich. Deine Kaution wird zurückgezahlt, wenn das Haar im vereinbarten Zustand zurückgegeben wird." },
  { selector: ".orn-step-title", index: 4, text: "Abholen und genießen" },
  { selector: ".orn-step-text", index: 4, text: "Hole dein BiziLuxe Clip-in-Set im Salon ab und genieße dein Event mit luxuriösem, nahtlosem Haar, das den ganzen Abend auffällt." },
  { selector: ".orn-step-title", index: 5, text: "Im Salon zurückgeben" },
  { selector: ".orn-step-text", index: 5, text: "Gib das Haar nach deinem Event in unserem Berliner Salon zurück. Nach Prüfung im vereinbarten Zustand erhältst du deine volle Kaution zurück." },
  { selector: ".orn-includes .orn-section-eyebrow", text: "Was du erhältst" },
  { selector: ".orn-includes .orn-section-title", html: "Alles <em>inklusive.</em>" },
  { selector: ".orn-includes .orn-section-sub", text: "Jeder Verleih ist ein komplettes Luxus-Erlebnis von Anfang bis Ende. Unser Team kümmert sich um jedes Detail, damit du dich auf deinen Moment konzentrieren kannst." },
  { selector: ".orn-includes-item", index: 0, text: "Professionelle Beratung zur Farbabstimmung" },
  { selector: ".orn-includes-item", index: 1, text: "Premium BiziLuxe Clip-in-Haarset" },
  { selector: ".orn-includes-item", index: 2, text: "Anpassung im Salon durch unsere Spezialistinnen" },
  { selector: ".orn-includes-item", index: 3, text: "Professionelle Styling-Empfehlung für deinen Anlass" },
  { selector: ".orn-includes-item", index: 4, text: "Abholung und Rückgabe im Berliner Salon" },
  { selector: ".orn-includes .orn-btn-dark", text: "Beratung buchen" },
  { selector: ".orn-includes-img-ph span", text: "BiziLuxe Kollektion" },
  { selector: ".orn-terms .orn-section-eyebrow", text: "Wichtige Informationen" },
  { selector: ".orn-terms .orn-section-title", html: "Verleih-<em>Bedingungen</em>" },
  { selector: ".orn-terms .orn-section-sub", text: "Bitte lies die folgenden Hinweise, bevor du deine Verleih-Beratung buchst." },
  { selector: ".orn-term-text", index: 0, text: "Nur mit Termin verfügbar. Walk-ins sind für den Verleih-Service nicht möglich." },
  { selector: ".orn-term-text", index: 1, text: "Nur Abholung und Rückgabe im Berliner Salon. Versand ist für diesen Service nicht verfügbar." },
  { selector: ".orn-term-text", index: 2, text: "Es fällt eine Verleihgebühr an, die während deiner Beratung im Salon bestätigt wird." },
  { selector: ".orn-term-text", index: 3, text: "Eine vollständig erstattbare Kaution ist erforderlich und wird nach sicherer Rückgabe des Haars zurückgezahlt." },
  { selector: ".orn-term-text", index: 4, text: "Je nach Verfügbarkeit. Für Hochzeiten und große Events empfehlen wir eine frühzeitige Buchung." },
  { selector: ".orn-term-text", index: 5, text: "Das Haar muss im vereinbarten Zustand zurückgegeben werden. Schäden können zum teilweisen oder vollständigen Einbehalt der Kaution führen." },
  { selector: ".orn-social .orn-section-eyebrow", text: "Verleih-Looks" },
  { selector: ".orn-social .orn-section-title", html: "Verleih-Looks &amp; <em>besondere Momente</em>" },
  { selector: ".orn-cta-eyebrow", text: "Dein besonderer Moment wartet" },
  { selector: ".orn-cta-title", html: "Bereit für deinen<br><em>besonderen Moment?</em>" },
  { selector: ".orn-cta-sub", text: "Buche eine private Verleih-Beratung und lass unser Team das perfekte BiziLuxe Clip-in-Set für deinen Anlass auswählen." },
  { selector: ".orn-btn-cta-primary", text: "Beratung zum Verleih buchen" },
  { selector: ".orn-btn-cta-outline", text: "Unser Team kontaktieren" },

  { selector: ".owhl-hero-img", attr: "alt", text: "OlivHairSupply Großhandel" },
  { selector: ".owhl-hero-eyebrow", text: "Großhandel" },
  { selector: ".owhl-hero-title", html: "Partner von <em>OlivHairSupply werden</em>" },
  { selector: ".owhl-whl-btns .owhl-btn-gold", text: "Großhandelspartner werden" },
  { selector: ".owhl-whl-btns .owhl-btn-dark", text: "Zum Großhandelsshop anmelden" },
  { selector: ".owhl-intro .owhl-eyebrow", text: "Das Programm" },
  { selector: ".owhl-intro .owhl-title", html: "Gemacht für <em>Profis</em>" },
  { selector: ".owhl-intro-lead", text: "Unser Großhandelsprogramm ist für Salons, Stylistinnen, Retailer und Profis gemacht, die Zugang zu hochwertigen BiziLuxe Produkten zu starken Konditionen suchen." },
  { selector: ".owhl-body", index: 0, text: "Wir arbeiten mit einem ausgewählten Netzwerk von Großhandelspartnern, die unseren Anspruch an Qualität und Kundenerlebnis teilen. Jede Bewerbung wird persönlich von unserem Team geprüft." },
  { selector: ".owhl-body", index: 1, text: "Nach deiner Freigabe erhältst du direkten Zugang zur vollständigen BiziLuxe Produktpalette, persönlichem Support und einem einfachen Bestellsystem, das dir Zeit spart." },
  { selector: ".owhl-who-tag", index: 0, text: "Salons" },
  { selector: ".owhl-who-tag", index: 1, text: "Stylistinnen" },
  { selector: ".owhl-who-tag", index: 2, text: "Retailer" },
  { selector: ".owhl-who-tag", index: 3, text: "Academies" },
  { selector: ".owhl-who-tag", index: 4, text: "Profis" },
  { selector: ".owhl-intro-img-ph span", text: "Großhandel" },
  { selector: ".owhl-benefits-header .owhl-eyebrow", text: "Programm-Vorteile" },
  { selector: ".owhl-benefits-title", html: "Was du <em>erhältst</em>" },
  { selector: ".owhl-benefits-sub", text: "Alles, was ein professionelles Business braucht, um Luxus-Haar zu führen und zu verkaufen." },
  { selector: ".owhl-benefit-title", index: 0, text: "Großhandelspreise" },
  { selector: ".owhl-benefit-text", index: 0, text: "Attraktive Großhandelskonditionen auf die gesamte BiziLuxe Range, exklusiv für freigegebene Partner." },
  { selector: ".owhl-benefit-title", index: 1, text: "Vollständige Produktpalette" },
  { selector: ".owhl-benefit-text", index: 1, text: "Zugang zu jedem BiziLuxe Produkt, jeder Struktur und Länge, inklusive Artikeln, die nicht öffentlich gelistet sind." },
  { selector: ".owhl-benefit-title", index: 2, text: "Priorisierter Zugang" },
  { selector: ".owhl-benefit-text", index: 2, text: "Großhandelspartner erhalten frühen Zugang zu neuen Drops, Restock-Hinweisen und limitierten Produkten." },
  { selector: ".owhl-benefit-title", index: 3, text: "Dedizierter Support" },
  { selector: ".owhl-benefit-text", index: 3, text: "Ein direkter Account-Kontakt für Bestellfragen, Produktfragen und laufende Betreuung." },
  { selector: ".owhl-benefit-title", index: 4, text: "Flexible Bestellung" },
  { selector: ".owhl-benefit-text", index: 4, text: "Einfache Bestellanfragen über dein Großhandels-Dashboard, zeitnah geprüft und bearbeitet." },
  { selector: ".owhl-steps-header .owhl-eyebrow", text: "So funktioniert es" },
  { selector: ".owhl-steps-header .owhl-title", html: "Vier einfache <em>Schritte</em>" },
  { selector: ".owhl-step-title", index: 0, text: "Bewerben" },
  { selector: ".owhl-step-text", index: 0, text: "Reiche deine Unternehmensdaten, Salon- oder Retail-Informationen und eine kurze Beschreibung deines Geschäfts ein." },
  { selector: ".owhl-step-title", index: 1, text: "Freigabe erhalten" },
  { selector: ".owhl-step-text", index: 1, text: "Unser Team prüft deine Bewerbung innerhalb von 3 bis 5 Werktagen und meldet sich mit einer Entscheidung." },
  { selector: ".owhl-step-title", index: 2, text: "Großhandelsshop öffnen" },
  { selector: ".owhl-step-text", index: 2, text: "Du erhältst deine Zugangsdaten und bekommst Zugriff auf dein persönliches Dashboard und deine Preise." },
  { selector: ".owhl-step-title", index: 3, text: "Bestellungen einreichen" },
  { selector: ".owhl-step-text", index: 3, text: "Durchsuche die vollständige BiziLuxe Range, lege Produkte in den Warenkorb, prüfe den Gesamtbetrag und sende deine Bestellung ab." },
  { selector: ".owhl-term-label", index: 0, text: "Mindestbestellung" },
  { selector: ".owhl-term-title", index: 0, text: "Bestellgrenzen" },
  { selector: ".owhl-term-text", index: 0, text: "Für alle Großhandelskonten gilt ein Mindestbestellwert. Die Grenzen werden nach Freigabe kommuniziert und anhand der Account-Aktivität überprüft." },
  { selector: ".owhl-term-label", index: 1, text: "Freigabe" },
  { selector: ".owhl-term-title", index: 1, text: "Ausgewählte Partnerschaft" },
  { selector: ".owhl-term-text", index: 1, text: "Wir prüfen jede Bewerbung sorgfältig. Wir arbeiten selektiv mit Unternehmen, die zu unseren Qualitätsstandards und Markenwerten passen." },
  { selector: ".owhl-term-label", index: 2, text: "Weiterverkauf" },
  { selector: ".owhl-term-title", index: 2, text: "Richtlinien für den Weiterverkauf" },
  { selector: ".owhl-term-text", index: 2, text: "BiziLuxe Produkte dürfen nur von freigegebenen Partnern weiterverkauft werden. Großhandelspreise dürfen nicht öffentlich gezeigt oder an andere Wiederverkäufer weitergegeben werden." },
  { selector: ".owhl-states-title", html: "Wo stehst <em>du?</em>" },
  { selector: ".owhl-states-sub", text: "Wähle den Weg, der zu dir passt." },
  { selector: ".owhl-state-tag", index: 0, text: "Neue Bewerbung" },
  { selector: ".owhl-state-title", index: 0, text: "Noch nicht registriert" },
  { selector: ".owhl-state-item", index: 0, text: "Großhandelsbewerbung ausfüllen" },
  { selector: ".owhl-state-item", index: 1, text: "Unternehmensdaten einreichen" },
  { selector: ".owhl-state-item", index: 2, text: "Prüfung durch unser Team abwarten" },
  { selector: ".owhl-state-item", index: 3, text: "Freigabe innerhalb von 3 bis 5 Werktagen erhalten" },
  { selector: ".owhl-state-tag", index: 1, text: "Freigegebener Partner" },
  { selector: ".owhl-state-title", index: 1, text: "Bereits freigegeben" },
  { selector: ".owhl-state-item", index: 4, text: "In dein Großhandelskonto einloggen" },
  { selector: ".owhl-state-item", index: 5, text: "Vollständige BiziLuxe Range ansehen" },
  { selector: ".owhl-state-item", index: 6, text: "Produkte in den Warenkorb legen" },
  { selector: ".owhl-state-item", index: 7, text: "Gesamtbetrag prüfen und Bestellung absenden" },
  { selector: ".owhl-state-tag", index: 2, text: "Fragen?" },
  { selector: ".owhl-state-title", index: 2, text: "Du brauchst mehr Informationen" },
  { selector: ".owhl-state-item", index: 8, text: "Fragen zum Programm?" },
  { selector: ".owhl-state-item", index: 9, text: "Nicht sicher, ob du dich qualifizierst?" },
  { selector: ".owhl-state-item", index: 10, text: "Möchtest du zuerst Konditionen besprechen?" },
  { selector: ".owhl-state-item", index: 11, text: "Unser Team antwortet innerhalb eines Werktags" },
  { selector: ".owhl-state-btn-primary", index: 0, text: "Jetzt bewerben" },
  { selector: ".owhl-state-btn-primary", index: 1, text: "Zum Shop anmelden" },
  { selector: ".owhl-state-btn-secondary", text: "Kontakt" },
  { selector: ".owhl-state-note", text: "Wir beantworten deine Fragen gern, bevor du dich bewirbst." },
  { selector: ".owhl-cta-eyebrow", text: "Bereit für eine Partnerschaft" },
  { selector: ".owhl-cta-title", html: "Starte deine <em>Großhandelsreise</em>" },
  { selector: ".owhl-cta-sub", text: "Bewirb dich jetzt für unser Großhandelsprogramm. Eine Premium-Produktpalette, attraktive Konditionen und ein Team, das dein Business unterstützt." },
  { selector: ".owhl-cta .owhl-btn-gold", text: "Großhandelspartner werden" },
  { selector: ".owhl-cta .owhl-btn-dark", text: "Zum Großhandelsshop anmelden" },

  { selector: "#owhl-apply-close", attr: "aria-label", text: "Schließen" },
  { selector: "#owhl-login-close", attr: "aria-label", text: "Schließen" },
  { selector: "#owhl-apply-overlay .owhl-modal-eyebrow", text: "Großhandelsbewerbung" },
  { selector: "#owhl-apply-overlay .owhl-modal-title", html: "Großhandels<em>partner werden</em>" },
  { selector: "#owhl-apply-overlay .owhl-modal-sub", text: "Fülle das Formular aus. Unser Team prüft jede Bewerbung persönlich und meldet sich innerhalb von 3 bis 5 Werktagen bei dir." },
  { selector: ".owhl-form-label", index: 0, text: "Vollständiger Name" },
  { selector: ".owhl-form-label", index: 1, text: "E-Mail-Adresse" },
  { selector: ".owhl-form-label", index: 2, text: "Telefonnummer" },
  { selector: ".owhl-form-label", index: 3, text: "Unternehmensname" },
  { selector: ".owhl-form-label", index: 4, text: "Unternehmensart" },
  { selector: ".owhl-form-label", index: 5, text: "Land" },
  { selector: ".owhl-form-label", index: 6, text: "Website oder Social Link" },
  { selector: ".owhl-form-label", index: 7, text: "Erwartetes monatliches Bestellvolumen" },
  { selector: ".owhl-form-label", index: 8, text: "USt-IdNr. (falls vorhanden)" },
  { selector: ".owhl-form-label", index: 9, text: "Erzähl uns von deinem Business" },
  { selector: "#whl-name", attr: "placeholder", text: "Dein vollständiger Name" },
  { selector: "#whl-business", attr: "placeholder", text: "Name deines Salons oder Unternehmens" },
  { selector: "#whl-about", attr: "placeholder", text: "Beschreibe dein Business, deine Kundinnen und wie du unsere Produkte einsetzen möchtest." },
  { selector: ".owhl-form-check-label", text: "Ich stimme zu, die OlivHairSupply Großhandelsbedingungen inklusive Weiterverkaufsbeschränkungen und Brand Guidelines einzuhalten." },
  { selector: "#owhl-apply-overlay .owhl-form-submit", text: "Bewerbung absenden" },
  { selector: "#owhl-apply-overlay .owhl-form-note", text: "Wir prüfen jede Bewerbung persönlich. Du hörst innerhalb von 3 bis 5 Werktagen von uns." },
  { selector: "#owhl-login-overlay .owhl-modal-eyebrow", text: "Großhandels-Login" },
  { selector: "#owhl-login-overlay .owhl-modal-title", html: "Zugang zu deinem <em>Großhandelsshop</em>" },
  { selector: "#owhl-login-overlay .owhl-modal-sub", text: "Gib deine Großhandels-Zugangsdaten ein. Diese erhältst du von OlivHairSupply, sobald deine Bewerbung bestätigt wurde." },
  { selector: ".owhl-form-label", index: 10, text: "E-Mail-Adresse" },
  { selector: ".owhl-form-label", index: 11, text: "Wholesale Access Code" },
  { selector: "#whl-login-code", attr: "placeholder", text: "Access Code eingeben" },
  { selector: "#owhl-login-error", text: "Die Angaben stimmen nicht. Bitte prüfe deine E-Mail-Adresse und deinen Access Code und versuche es erneut." },
  { selector: "#owhl-login-overlay .owhl-form-submit", text: "Großhandelsshop öffnen" },
  { selector: "#owhl-login-overlay .owhl-form-note", html: 'Noch nicht freigegeben? <a href="#" onclick="owhlCloseLogin(); owhlOpenApply(); return false;">Für ein Großhandelskonto bewerben.</a>' },

  { selector: ".oaff-hero-eyebrow", text: "OlivHairSupply Affiliate-Programm" },
  { selector: ".oaff-hero-title", html: "Verdienen. Einfluss nutzen. <em>Wachsen.</em>" },
  { selector: ".oaff-hero-sub", text: "Verwandle deine Reichweite in Einkommen mit dem OlivHairSupply Affiliate-Programm." },
  { selector: ".oaff-hero .oaff-btn-gold", text: "Affiliate werden" },
  { selector: ".oaff-hero .oaff-btn-dark", text: "Zum Dashboard anmelden" },
  { selector: ".oaff-intro .oaff-eyebrow", text: "Das Programm" },
  { selector: ".oaff-intro .oaff-title", html: "Mehr als ein <em>Affiliate-Programm</em>" },
  { selector: ".oaff-intro-lead", text: "Hier geht es nicht nur darum, Links zu teilen." },
  { selector: ".oaff-body", index: 0, text: "Als OlivHairSupply Affiliate wirst du Teil einer Luxus-Haar-Bewegung — du bewirbst Premium-BiziLuxe Produkte, inspirierst deine Community und verdienst Provision für jeden Verkauf, den du generierst." },
  { selector: ".oaff-body", index: 1, text: "Wir arbeiten mit Menschen, die unsere Markenwerte verkörpern — Qualität, Selbstbewusstsein und echten Einfluss. Wenn das zu dir passt, möchten wir von dir hören." },
  { selector: ".oaff-intro-img-ph span", text: "Affiliate" },
  { selector: ".oaff-benefits-header .oaff-eyebrow", text: "Deine Vorteile" },
  { selector: ".oaff-benefits-title", html: "Was du <em>erhältst</em>" },
  { selector: ".oaff-benefits-sub", text: "Alles, was du brauchst, um mit einer Marke, an die du glaubst, echtes Einkommen aufzubauen." },
  { selector: ".oaff-benefit-title", index: 0, text: "Attraktive Provision" },
  { selector: ".oaff-benefit-text", index: 0, text: "Verdiene eine starke Provision auf jeden qualifizierten Verkauf, den du generierst. Performance wird belohnt — je mehr du bewirbst, desto mehr kannst du verdienen." },
  { selector: ".oaff-benefit-title", index: 1, text: "Dein eigener Link und Code" },
  { selector: ".oaff-benefit-text", index: 1, text: "Du erhältst einen persönlichen Affiliate-Link und Rabattcode für deine Community. Deine Verkäufe werden präzise und transparent getrackt." },
  { selector: ".oaff-benefit-title", index: 2, text: "Exklusiver Produktzugang" },
  { selector: ".oaff-benefit-text", index: 2, text: "Erhalte frühen Zugang zu neuen BiziLuxe Drops und Kollektionen, bevor sie öffentlich live gehen. Teile als Erste, was kommt." },
  { selector: ".oaff-benefit-title", index: 3, text: "Priorität bei Schulungen" },
  { selector: ".oaff-benefit-text", index: 3, text: "Freigegebene Affiliates erhalten bevorzugten Zugang zu OlivHairSupply Academy Schulungen, Masterclasses und Brand Events." },
  { selector: ".oaff-benefit-title", index: 4, text: "Sichtbarkeit auf Brand-Kanälen" },
  { selector: ".oaff-benefit-text", index: 4, text: "Starke Affiliates können auf unseren Social Channels, im Newsletter und in Brand-Inhalten gefeatured werden — und wachsen mit unserer Reichweite." },
  { selector: ".oaff-benefit-title", index: 5, text: "Langfristige Partnerschaft" },
  { selector: ".oaff-benefit-text", index: 5, text: "Wir investieren langfristig in unsere Affiliate-Community. Wenn OlivHairSupply wächst, wachsen unsere Affiliates mit." },
  { selector: ".oaff-clarity-title", html: "Ein paar Dinge, die du <em>wissen solltest</em>" },
  { selector: ".oaff-clarity-sub", text: "Wir kommunizieren klar. Das ist nicht Teil des Programms." },
  { selector: ".oaff-clarity-text", index: 0, html: "<strong>Kein garantiertes Einkommen.</strong> Das Programm ist performancebasiert. Deine Einnahmen spiegeln Einsatz und Qualität deiner Promotion wider." },
  { selector: ".oaff-clarity-text", index: 1, html: "<strong>Keine automatische Freigabe.</strong> Jede Bewerbung wird von unserem Team geprüft. Wir wählen selektiv aus, um den Standard unserer Marke zu schützen." },
  { selector: ".oaff-clarity-text", index: 2, html: "<strong>Keine missbräuchliche Nutzung von Brand Assets.</strong> Alle OlivHairSupply und BiziLuxe Brandings müssen gemäß unseren Affiliate Guidelines genutzt werden." },
  { selector: ".oaff-clarity-text", index: 3, html: "<strong>Kein Spam oder unethische Promotion.</strong> Wir erwarten, dass unsere Affiliates authentisch und jederzeit im Einklang mit unseren Markenwerten werben." },
  { selector: ".oaff-steps-header .oaff-eyebrow", text: "So funktioniert es" },
  { selector: ".oaff-steps-header .oaff-title", html: "Vier einfache <em>Schritte</em>" },
  { selector: ".oaff-step-title", index: 0, text: "Bewerben" },
  { selector: ".oaff-step-text", index: 0, text: "Reiche deine Daten, Plattform-Links und eine kurze Vorstellung ein. Zeig uns, wer du bist und wer deine Community ist." },
  { selector: ".oaff-step-title", index: 1, text: "Freigabe erhalten" },
  { selector: ".oaff-step-text", index: 1, text: "Unser Team prüft deine Bewerbung innerhalb von 3 bis 5 Werktagen. Wir achten auf Markenfit und echte Community-Bindung." },
  { selector: ".oaff-step-title", index: 2, text: "Link und Code erhalten" },
  { selector: ".oaff-step-text", index: 2, text: "Nach Freigabe erhältst du deinen persönlichen Affiliate-Link, deinen Rabattcode und Zugang zu deinem Performance-Dashboard." },
  { selector: ".oaff-step-title", index: 3, text: "Verdienen starten" },
  { selector: ".oaff-step-text", index: 3, text: "Teile, bewirb und verdiene Provision auf jeden qualifizierten Verkauf. Tracke deine Performance in Echtzeit über dein Affiliate-Dashboard." },
  { selector: ".oaff-who .oaff-eyebrow", text: "Für wen es ist" },
  { selector: ".oaff-who-title", html: "Gemacht für <em>Creators</em>" },
  { selector: ".oaff-who-body", text: "Wir arbeiten mit Menschen, die eine authentische Verbindung zu Beauty, Haar und Lifestyle haben. Du brauchst keine Millionen Follower — du brauchst echten Einfluss und eine Community, die dir vertraut." },
  { selector: ".oaff-who-item", index: 0, html: '<div class="oaff-who-item-dot"></div>Content Creators' },
  { selector: ".oaff-who-item", index: 1, html: '<div class="oaff-who-item-dot"></div>Influencerinnen' },
  { selector: ".oaff-who-item", index: 2, html: '<div class="oaff-who-item-dot"></div>Hair Stylists' },
  { selector: ".oaff-who-item", index: 3, html: '<div class="oaff-who-item-dot"></div>Beauty Professionals' },
  { selector: ".oaff-who-item", index: 4, html: '<div class="oaff-who-item-dot"></div>Unternehmerinnen' },
  { selector: ".oaff-who-img-ph span", text: "Creators" },
  { selector: ".oaff-proof-header .oaff-eyebrow", text: "Social Proof" },
  { selector: ".oaff-proof-header .oaff-title", html: "Sieh es in <em>Aktion</em>" },
  { selector: ".oaff-proof-video-label", text: "Video-Thumbnail im Customizer hinzufügen" },
  { selector: ".oaff-states-header .oaff-eyebrow", text: "Dein Zugang" },
  { selector: ".oaff-states-title", html: "Wo stehst <em>du?</em>" },
  { selector: ".oaff-states-sub", text: "Wähle den Weg, der zu dir passt." },
  { selector: ".oaff-state-tag", index: 0, text: "Neue Bewerbung" },
  { selector: ".oaff-state-title", index: 0, text: "Noch nicht registriert" },
  { selector: ".oaff-state-list-item", index: 0, text: "Bewerbungsformular ausfüllen" },
  { selector: ".oaff-state-list-item", index: 1, text: "Profil- und Plattformdetails einreichen" },
  { selector: ".oaff-state-list-item", index: 2, text: "Prüfung durch unser Team abwarten" },
  { selector: ".oaff-state-list-item", index: 3, text: "Freigabe innerhalb von 3 bis 5 Werktagen erhalten" },
  { selector: ".oaff-state-tag", index: 1, text: "Freigegebener Affiliate" },
  { selector: ".oaff-state-title", index: 1, text: "Bereits freigegeben" },
  { selector: ".oaff-state-list-item", index: 4, text: "Affiliate-Dashboard öffnen" },
  { selector: ".oaff-state-list-item", index: 5, text: "Deinen Link und Rabattcode ansehen" },
  { selector: ".oaff-state-list-item", index: 6, text: "Performance und Provisionen tracken" },
  { selector: ".oaff-state-list-item", index: 7, text: "Exklusive Produkt- und Event-Updates erhalten" },
  { selector: ".oaff-state-tag", index: 2, text: "Nicht sicher?" },
  { selector: ".oaff-state-title", index: 2, text: "Du brauchst Hilfe?" },
  { selector: ".oaff-state-list-item", index: 8, text: "Nicht sicher, ob du dich qualifizierst?" },
  { selector: ".oaff-state-list-item", index: 9, text: "Fragen zum Programm?" },
  { selector: ".oaff-state-list-item", index: 10, text: "Möchtest du vor der Bewerbung mehr erfahren?" },
  { selector: ".oaff-state-list-item", index: 11, text: "Unser Team beantwortet jede Frage gern" },
  { selector: ".oaff-state-btn-primary", index: 0, text: "Jetzt bewerben" },
  { selector: ".oaff-state-btn-primary", index: 1, text: "Zum Dashboard anmelden" },
  { selector: ".oaff-state-btn-secondary", text: "Kontakt" },
  { selector: ".oaff-state-note", text: "Wir prüfen alle Anfragen und antworten innerhalb eines Werktags." },
  { selector: ".oaff-cta-eyebrow", text: "Dein nächster Schritt" },
  { selector: ".oaff-cta-title", html: "Bereit, <em>dabei zu sein?</em>" },
  { selector: ".oaff-cta-sub", text: "Bewirb dich jetzt und verdiene mit OlivHairSupply. Eine Marke, die es wert ist, beworben zu werden. Eine Community, die es wert ist, Teil davon zu sein." },
  { selector: ".oaff-cta .oaff-btn-gold", text: "Affiliate werden" },
  { selector: ".oaff-cta .oaff-btn-dark", text: "Zum Dashboard anmelden" },

  { selector: "#oaff-apply-close", attr: "aria-label", text: "Schließen" },
  { selector: "#oaff-dash-close", attr: "aria-label", text: "Schließen" },
  { selector: "#oaff-apply-overlay .oaff-modal-eyebrow", text: "Bewerbung" },
  { selector: "#oaff-apply-overlay .oaff-modal-title", html: "Affiliate <em>werden</em>" },
  { selector: "#oaff-apply-overlay .oaff-modal-sub", text: "Fülle deine Daten aus. Unser Team prüft deine Bewerbung innerhalb von 3 bis 5 Werktagen und kontaktiert dich direkt." },
  { selector: ".oaff-form-label", index: 0, text: "Vollständiger Name" },
  { selector: ".oaff-form-label", index: 1, text: "E-Mail-Adresse" },
  { selector: ".oaff-form-label", index: 2, text: "Telefonnummer" },
  { selector: ".oaff-form-label", index: 3, text: "Hauptplattform" },
  { selector: ".oaff-form-label", index: 4, text: "Social Media Handle" },
  { selector: ".oaff-form-label", index: 5, text: "Followerzahl" },
  { selector: ".oaff-form-label", index: 6, text: "Profil-Link" },
  { selector: ".oaff-form-label", index: 7, text: "Erzähl uns von dir und deiner Community" },
  { selector: "#aff-name", attr: "placeholder", text: "Dein vollständiger Name" },
  { selector: "#aff-platform option", index: 0, text: "Plattform auswählen" },
  { selector: "#aff-followers option", index: 0, text: "Bereich auswählen" },
  { selector: "#aff-followers option", index: 1, text: "Unter 5.000" },
  { selector: "#aff-followers option", index: 2, text: "5.000 bis 10.000" },
  { selector: "#aff-followers option", index: 3, text: "10.000 bis 50.000" },
  { selector: "#aff-followers option", index: 4, text: "50.000 bis 100.000" },
  { selector: "#aff-followers option", index: 5, text: "Über 100.000" },
  { selector: "#aff-about", attr: "placeholder", text: "Beschreibe kurz deinen Content, deine Community und warum du mit OlivHairSupply zusammenarbeiten möchtest." },
  { selector: ".oaff-form-check-label", text: "Ich stimme zu, OlivHairSupply authentisch und gemäß den Brand Guidelines zu bewerben." },
  { selector: "#oaff-apply-overlay .oaff-form-submit", text: "Bewerbung absenden" },
  { selector: "#oaff-apply-overlay .oaff-form-note", text: "Wir prüfen jede Bewerbung persönlich. Du hörst innerhalb von 3 bis 5 Werktagen von uns." },
  { selector: "#oaff-login-panel .oaff-modal-eyebrow", text: "Affiliate Dashboard" },
  { selector: "#oaff-login-panel .oaff-modal-title", html: "In dein <em>Dashboard</em> einloggen" },
  { selector: "#oaff-login-panel .oaff-modal-sub", text: "Gib deine Affiliate-Zugangsdaten ein. Diese erhältst du von OlivHairSupply, sobald deine Bewerbung bestätigt wurde." },
  { selector: ".oaff-form-label", index: 8, text: "E-Mail-Adresse" },
  { selector: ".oaff-form-label", index: 9, text: "Affiliate Access Code" },
  { selector: "#dash-code", attr: "placeholder", text: "Access Code eingeben" },
  { selector: "#oaff-login-error", text: "Die Angaben stimmen nicht. Bitte prüfe deine E-Mail-Adresse und deinen Access Code und versuche es erneut." },
  { selector: "#oaff-login-panel .oaff-form-submit", text: "Dashboard öffnen" },
  { selector: "#oaff-login-panel .oaff-form-note", html: 'Noch nicht freigegeben? <a href="#" onclick="closeDash(); openApply(); return false;">Für das Programm bewerben.</a>' },
  { selector: ".oaff-portal-home", text: "Zurück zur Website" },
  { selector: ".oaff-dash-logout", text: "Abmelden" },
  { selector: ".oaff-dash-stat-label", index: 0, text: "Gesamtumsatz" },
  { selector: ".oaff-dash-stat-label", index: 1, text: "Gesamteinnahmen" },
  { selector: ".oaff-dash-stat-label", index: 2, text: "Ausstehende Auszahlung" },
  { selector: ".oaff-dash-stat-label", index: 3, text: "Link-Klicks" },
  { selector: ".oaff-dash-stat-label", index: 4, text: "Conversion" },
  { selector: ".oaff-dash-stat-label", index: 5, text: "Status" },
  { selector: ".oaff-dash-tool-label", index: 0, text: "Dein Affiliate-Link" },
  { selector: ".oaff-dash-tool-label", index: 1, text: "Dein Rabattcode" },
  { selector: ".oaff-dash-copy-btn", text: "Kopieren" },
  { selector: ".oaff-dash-section-title", index: 0, text: "Aktuelle Bestellungen" },
  { selector: ".oaff-dash-section-title", index: 1, text: "Auszahlungshistorie" },
  { selector: ".oaff-dash-section-title", index: 2, text: "Marketing Assets" },
  { selector: ".oaff-dash-section-title", index: 3, text: "So bewirbst du" },
  { selector: ".oaff-dash-support-title", text: "Brauchst du Hilfe?" },
  { selector: ".oaff-dash-support-text", text: "Bei Fragen zu deinem Konto, Zahlungen oder Marketingmaterialien kontaktiere direkt unser Affiliate-Team." },
  { selector: ".oaff-dash-support-btn-primary", text: "E-Mail senden" },

  { selector: ".oappt-hero-img", attr: "alt", text: "Termin vereinbaren" },
  { selector: ".oappt-hero-eyebrow", text: "Termin" },
  { selector: ".oappt-hero-title", html: "Buche dein <em>Erlebnis</em>" },
  { selector: ".oappt-whl-btns .oappt-btn-gold", text: "Shop" },
  { selector: ".oappt-whl-btns .oappt-btn-dark", text: "Affiliate werden" },
  { selector: ".oappt-confirm-title", html: "Anfrage <em>erhalten</em>" },
  { selector: ".oappt-confirm-sub", text: "Deine Terminanfrage ist eingegangen. Unser Team bestätigt deine Buchung innerhalb von 24 Stunden per E-Mail oder WhatsApp." },
  { selector: ".oappt-confirm-btn-dark", text: "Zur Startseite" },
  { selector: ".oappt-confirm-btn-out", text: "BiziLuxe shoppen" },
  { selector: "#oappt-step-1 .oappt-step-title", html: "Wähle deinen <em>Standort</em>" },
  { selector: "#oappt-step-1 .oappt-step-sub", text: "Wähle deinen bevorzugten OlivHairSupply Standort. Preise können je nach Standort variieren." },
  { selector: ".oappt-location-name", index: 0, text: "Schöneberg" },
  { selector: ".oappt-location-name", index: 1, text: "Kurfürstendamm" },
  { selector: ".oappt-location-address", index: 0, html: "OlivHairSupply<br>Winterfeldtstraße 7<br>10781 Berlin, Schöneberg<br>Montag bis Samstag" },
  { selector: ".oappt-location-address", index: 1, html: "OlivHairSupply<br>Kurfürstendamm 115B<br>10711 Berlin, Halensee<br>Dienstag bis Samstag" },
  { selector: "#oappt-err-1", text: "Bitte wähle einen Standort, um fortzufahren." },
  { selector: "#oappt-step-2 .oappt-step-title", html: "Wähle deinen <em>Service</em>" },
  { selector: "#oappt-step-2 .oappt-step-sub", text: "Wähle die Service-Kategorie, die du buchen möchtest." },
  { selector: "#oappt-err-2", text: "Bitte wähle einen Service, um fortzufahren." },
  { selector: "#oappt-step-3 .oappt-step-title", html: "Konfiguriere deinen <em>Service</em>" },
  { selector: "#oappt-step-3 .oappt-step-sub", text: "Wähle deine Optionen. Deine geschätzte Gesamtsumme aktualisiert sich während der Auswahl." },
  { selector: "#oappt-err-3", text: "Bitte fülle alle erforderlichen Auswahlen aus." },
  { selector: "#oappt-step-4 .oappt-step-title", html: "Wähle deine <em>Stylistin</em>" },
  { selector: "#oappt-step-4 .oappt-step-sub", text: "Wähle die Spezialistin, mit der du arbeiten möchtest." },
  { selector: "#oappt-err-4", text: "Bitte wähle eine Stylistin, um fortzufahren." },
  { selector: "#oappt-step-5 .oappt-step-title", html: "Wähle ein <em>Datum</em>" },
  { selector: "#oappt-step-5 .oappt-step-sub", text: "Tage mit goldenem Punkt haben Verfügbarkeit. Wir sind Montag bis Samstag geöffnet." },
  { selector: ".oappt-cal-day-label", index: 0, text: "Mo" },
  { selector: ".oappt-cal-day-label", index: 1, text: "Di" },
  { selector: ".oappt-cal-day-label", index: 2, text: "Mi" },
  { selector: ".oappt-cal-day-label", index: 3, text: "Do" },
  { selector: ".oappt-cal-day-label", index: 4, text: "Fr" },
  { selector: ".oappt-cal-day-label", index: 5, text: "Sa" },
  { selector: ".oappt-cal-day-label", index: 6, text: "So" },
  { selector: ".oappt-cal-legend-item", index: 0, html: '<div class="oappt-cal-legend-dot" style="background:#B68A45;"></div>Verfügbar' },
  { selector: ".oappt-cal-legend-item", index: 1, html: '<div class="oappt-cal-legend-dot" style="background:#D0C4B4;"></div>Nicht verfügbar' },
  { selector: ".oappt-cal-legend-item", index: 2, html: '<div class="oappt-cal-legend-dot" style="background:#2B2620;"></div>Ausgewählt' },
  { selector: "#oappt-err-5", text: "Bitte wähle ein Datum, um fortzufahren." },
  { selector: "#oappt-step-6 .oappt-step-title", html: "Wähle eine <em>Uhrzeit</em>" },
  { selector: "#oappt-step-6 .oappt-step-sub", text: "Verfügbare Zeiten für deine ausgewählte Stylistin und dein Datum." },
  { selector: ".oappt-slots-note", text: "Alle Zeiten sind Berliner Ortszeit (CET/CEST). Bitte sei 5 Minuten vor deinem Termin da." },
  { selector: "#oappt-err-6", text: "Bitte wähle eine Uhrzeit, um fortzufahren." },
  { selector: "#oappt-step-7 .oappt-step-title", html: "Deine <em>Daten</em>" },
  { selector: "#oappt-step-7 .oappt-step-sub", text: "Bitte gib deine Kontaktdaten ein, damit wir deinen Termin bestätigen können." },
  { selector: ".oappt-form-label", index: 0, text: "Vollständiger Name" },
  { selector: ".oappt-form-label", index: 1, text: "E-Mail-Adresse" },
  { selector: ".oappt-form-label", index: 2, text: "Telefonnummer" },
  { selector: ".oappt-form-label", index: 3, text: "Zusätzliche Hinweise (optional)" },
  { selector: "#oappt-full-name", attr: "placeholder", text: "Dein vollständiger Name" },
  { selector: "#oappt-notes", attr: "placeholder", text: "Allergien, besondere Wünsche oder alles, was wir wissen sollten..." },
  { selector: "#oappt-err-7", text: "Bitte fülle alle Pflichtfelder korrekt aus." },
  { selector: "#oappt-step-8 .oappt-step-title", html: "Bestätige deinen <em>Termin</em>" },
  { selector: "#oappt-step-8 .oappt-step-sub", text: "Bitte prüfe deine Buchungsdetails, bevor du deine Anfrage absendest." },
  { selector: ".oappt-booking-note p", html: "<strong>Dies ist eine Buchungsanfrage.</strong> Unser Team bestätigt deinen Termin innerhalb von 24 Stunden per E-Mail oder WhatsApp. Zu diesem Zeitpunkt ist keine Zahlung erforderlich." },
  { selector: ".oappt-btn-request", text: "Buchung anfragen" },
  { selector: ".oappt-btn-next", text: "Weiter" },
  { selector: ".oappt-btn-back", text: "Zurück" },
  { selector: "#oappt-step-7 .oappt-btn-next", text: "Buchung prüfen" },
  { selector: ".oappt-progress-label", index: 0, text: "Standort" },
  { selector: ".oappt-progress-label", index: 1, text: "Service" },
  { selector: ".oappt-progress-label", index: 2, text: "Optionen" },
  { selector: ".oappt-progress-label", index: 3, text: "Stylistin" },
  { selector: ".oappt-progress-label", index: 4, text: "Datum" },
  { selector: ".oappt-progress-label", index: 5, text: "Uhrzeit" },
  { selector: ".oappt-progress-label", index: 6, text: "Daten" },
  { selector: ".oappt-progress-label", index: 7, text: "Bestätigung" },
  { selector: ".oappt-config-label", index: 0, text: "Service-Optionen" },
  { selector: ".oappt-config-label", index: 1, text: "Haar" },
  { selector: ".oappt-field-label", index: 0, text: "Auswahl" },
  { selector: ".oappt-radio-option", index: 0, text: "Ich bringe mein eigenes Haar mit" },
  { selector: ".oappt-radio-option", index: 1, text: "Ich möchte BiziLuxe Haar kaufen" },
  { selector: ".oappt-field-label", index: 1, text: "Haartyp" },
  { selector: ".oappt-field-label", index: 2, text: "Haarlänge (50 g pro Bundle)" },
  { selector: ".oappt-field-label", index: 3, text: "Anzahl Bundles" },
  { selector: ".oappt-field-label", index: 4, text: "Haarfarbe" },
  { selector: ".oappt-summary-title", text: "Deine Buchung" },
  { selector: ".oappt-summary-subtitle", text: "Zusammenfassung" },
  { selector: ".oappt-summary-empty", text: "Wähle einen Standort, um zu beginnen." },
  { selector: ".oappt-summary-total-label", text: "Geschätzte Gesamtsumme" },
];

export function translateAttributes(element: Element, pairs: [string, string][]) {
  for (const attribute of TRANSLATABLE_ATTRIBUTES) {
    const current = element.getAttribute(attribute);
    if (!current) continue;
    let next = current;
    for (const [from, to] of pairs) {
      if (next.includes(from)) next = next.split(from).join(to);
    }
    if (next !== current) element.setAttribute(attribute, next);
  }
}

export function applyManualPageOverrides(root: ParentNode, lang: "de" | "en") {
  const observerRoot = root instanceof HTMLElement ? root : null;

  for (const override of HOME_PAGE_DE_OVERRIDES) {
    const matches = Array.from(root.querySelectorAll<HTMLElement>(override.selector));
    const elements = override.index === undefined ? matches : matches[override.index] ? [matches[override.index]] : [];

    for (const element of elements) {
      if (override.attr) {
        const originalKey = `ohsOriginal${override.attr.replace(/[^a-z]/gi, "")}`;
        if (!(originalKey in element.dataset)) {
          element.dataset[originalKey] = element.getAttribute(override.attr) || "";
        }
        const next = lang === "de" ? override.text || "" : element.dataset[originalKey] || "";
        if (element.getAttribute(override.attr) !== next) element.setAttribute(override.attr, next);
        continue;
      }

      if (!("ohsOriginalHtml" in element.dataset)) {
        element.dataset.ohsOriginalHtml = element.innerHTML;
      }

      if (lang === "de") {
        if (override.html !== undefined && element.innerHTML !== override.html) element.innerHTML = override.html;
        else if (override.html === undefined && element.textContent !== (override.text || "")) element.textContent = override.text || "";
      } else {
        const original = element.dataset.ohsOriginalHtml || "";
        if (element.innerHTML !== original) element.innerHTML = original;
      }
    }
  }

  if (!observerRoot) return;

  const existing = (observerRoot as HTMLElement & { ohsManualObserver?: MutationObserver }).ohsManualObserver;
  if (lang === "en") {
    existing?.disconnect();
    delete (observerRoot as HTMLElement & { ohsManualObserver?: MutationObserver }).ohsManualObserver;
    return;
  }

  if (existing || typeof MutationObserver === "undefined") return;
  let pending = false;
  const observer = new MutationObserver(() => {
    if (pending) return;
    pending = true;
    window.requestAnimationFrame(() => {
      pending = false;
      applyManualPageOverrides(observerRoot, "de");
    });
  });
  observer.observe(observerRoot, { childList: true, subtree: true });
  (observerRoot as HTMLElement & { ohsManualObserver?: MutationObserver }).ohsManualObserver = observer;
}
