export const MANAGED_PAGES = [
  { key: "home", label: "Home Page", file: "home.html", path: "/" },
  { key: "shop", label: "Shop", file: "shop.html", path: "/shop" },
  { key: "pages-about", label: "About Us", file: "pages-about.html", path: "/pages/about" },
  { key: "pages-services", label: "Services", file: "pages-services.html", path: "/pages/services" },
  { key: "pages-training", label: "Training", file: "pages-training.html", path: "/training" },
  { key: "appointments", label: "Appointments", file: "appointments.html", path: "/appointments" },
  { key: "affiliate", label: "Affiliate", file: "affiliate.html", path: "/affiliate" },
  { key: "wholesale", label: "Wholesale", file: "wholesale.html", path: "/wholesale" },
  { key: "pages-rentals", label: "Rentals", file: "pages-rentals.html", path: "/pages/rentals" },
  { key: "pages-social-responsibility", label: "Social Responsibility", file: "pages-social-responsibility.html", path: "/pages/social-responsibility" },
  { key: "blogs-journal", label: "Journal", file: "blogs-journal.html", path: "/blogs/journal" },
  { key: "pages-careers", label: "Careers", file: "pages-careers.html", path: "/pages/careers" },
  { key: "pages-press", label: "Press", file: "pages-press.html", path: "/pages/press" },
];
